/**
 * Seed: discovery_schools — the School Discovery universe.
 *
 * Curated dataset of US colleges with MEN'S SOCCER programs, spanning
 * D1 / D2 / D3 / NAIA / JUCO. Division and state are authored accurately;
 * region is DERIVED from state via STATE_REGION so the convention is applied
 * uniformly (Northeast = New England + NY; Mid-Atlantic = NJ/PA/MD/DE/DC/VA/WV).
 * academic_band, enrollment_band, and has_engineering are best-effort v1
 * judgment calls, per spec — facets guide browse, they are not gospel.
 *
 * Idempotent: truncates discovery_schools then bulk-inserts. Safe to re-run.
 *
 * Run: npx tsx supabase/scripts/seed-discovery-schools.ts
 */
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

const env = readFileSync('.env.local', 'utf8')
const getEnv = (k: string) =>
  (env.match(new RegExp(`^${k}=(.*)$`, 'm'))?.[1] || '').trim().replace(/^["']|["']$/g, '')

const sb = createClient(getEnv('NEXT_PUBLIC_SUPABASE_URL'), getEnv('SUPABASE_SERVICE_ROLE_KEY'))

type Region = 'Northeast' | 'Mid-Atlantic' | 'Southeast' | 'Midwest' | 'Southwest' | 'West'
const STATE_REGION: Record<string, Region> = {
  // Northeast = New England + NY
  CT: 'Northeast', ME: 'Northeast', MA: 'Northeast', NH: 'Northeast', RI: 'Northeast', VT: 'Northeast', NY: 'Northeast',
  // Mid-Atlantic
  NJ: 'Mid-Atlantic', PA: 'Mid-Atlantic', MD: 'Mid-Atlantic', DE: 'Mid-Atlantic', DC: 'Mid-Atlantic', VA: 'Mid-Atlantic', WV: 'Mid-Atlantic',
  // Southeast
  NC: 'Southeast', SC: 'Southeast', GA: 'Southeast', FL: 'Southeast', AL: 'Southeast', MS: 'Southeast', TN: 'Southeast', KY: 'Southeast', AR: 'Southeast', LA: 'Southeast',
  // Midwest
  OH: 'Midwest', MI: 'Midwest', IN: 'Midwest', IL: 'Midwest', WI: 'Midwest', MN: 'Midwest', IA: 'Midwest', MO: 'Midwest', ND: 'Midwest', SD: 'Midwest', NE: 'Midwest', KS: 'Midwest',
  // Southwest
  TX: 'Southwest', OK: 'Southwest', NM: 'Southwest', AZ: 'Southwest',
  // West
  CO: 'West', WY: 'West', MT: 'West', ID: 'West', UT: 'West', NV: 'West', WA: 'West', OR: 'West', CA: 'West', AK: 'West', HI: 'West',
}

// Enrollment codes → band; Academic codes → band
const ENR = { 1: 'under_2k', 2: '2k_5k', 3: '5k_15k', 4: 'over_15k' } as const
const ACA = { m: 'most_selective', h: 'highly_selective', s: 'selective', a: 'accessible' } as const

type Enr = keyof typeof ENR
type Aca = keyof typeof ACA
// [name, short|null, conference|null, state, enrollmentCode, academicCode, hasEngineering(0/1), city|null]
type Row = [string, string | null, string | null, string, Enr, Aca, 0 | 1, string | null]

// ─── D1 ────────────────────────────────────────────────────────────────────
const D1: Row[] = [
  // ACC
  ['Boston College', 'BC', 'ACC', 'MA', 3, 'm', 1, 'Chestnut Hill'],
  ['Clemson', 'Clemson', 'ACC', 'SC', 4, 'h', 1, 'Clemson'],
  ['Duke', 'Duke', 'ACC', 'NC', 3, 'm', 1, 'Durham'],
  ['Louisville', 'Louisville', 'ACC', 'KY', 4, 's', 1, 'Louisville'],
  ['NC State', 'NC State', 'ACC', 'NC', 4, 'h', 1, 'Raleigh'],
  ['Notre Dame', 'Notre Dame', 'ACC', 'IN', 3, 'm', 1, 'Notre Dame'],
  ['Pittsburgh', 'Pitt', 'ACC', 'PA', 4, 'h', 1, 'Pittsburgh'],
  ['SMU', 'SMU', 'ACC', 'TX', 3, 's', 1, 'Dallas'],
  ['Stanford', 'Stanford', 'ACC', 'CA', 3, 'm', 1, 'Stanford'],
  ['Syracuse', 'Syracuse', 'ACC', 'NY', 4, 'h', 1, 'Syracuse'],
  ['Virginia', 'UVA', 'ACC', 'VA', 4, 'm', 1, 'Charlottesville'],
  ['Virginia Tech', 'Virginia Tech', 'ACC', 'VA', 4, 'h', 1, 'Blacksburg'],
  ['Wake Forest', 'Wake Forest', 'ACC', 'NC', 3, 'm', 0, 'Winston-Salem'],
  ['California', 'Cal', 'ACC', 'CA', 4, 'h', 1, 'Berkeley'],
  // Big Ten
  ['Indiana', 'Indiana', 'Big Ten', 'IN', 4, 's', 1, 'Bloomington'],
  ['Maryland', 'Maryland', 'Big Ten', 'MD', 4, 'h', 1, 'College Park'],
  ['Michigan', 'Michigan', 'Big Ten', 'MI', 4, 'h', 1, 'Ann Arbor'],
  ['Michigan State', 'Michigan St', 'Big Ten', 'MI', 4, 's', 1, 'East Lansing'],
  ['Northwestern', 'Northwestern', 'Big Ten', 'IL', 3, 'm', 1, 'Evanston'],
  ['Ohio State', 'Ohio St', 'Big Ten', 'OH', 4, 's', 1, 'Columbus'],
  ['Penn State', 'Penn St', 'Big Ten', 'PA', 4, 'h', 1, 'University Park'],
  ['Rutgers', 'Rutgers', 'Big Ten', 'NJ', 4, 's', 1, 'Piscataway'],
  ['UCLA', 'UCLA', 'Big Ten', 'CA', 4, 'h', 1, 'Los Angeles'],
  ['Washington', 'Washington', 'Big Ten', 'WA', 4, 'h', 1, 'Seattle'],
  ['Wisconsin', 'Wisconsin', 'Big Ten', 'WI', 4, 'h', 1, 'Madison'],
  ['Oregon', 'Oregon', 'Big Ten', 'OR', 4, 's', 1, 'Eugene'],
  // Big East
  ['Butler', 'Butler', 'Big East', 'IN', 3, 's', 1, 'Indianapolis'],
  ['Creighton', 'Creighton', 'Big East', 'NE', 3, 'h', 1, 'Omaha'],
  ['DePaul', 'DePaul', 'Big East', 'IL', 3, 's', 0, 'Chicago'],
  ['Georgetown', 'Georgetown', 'Big East', 'DC', 3, 'm', 0, 'Washington'],
  ['Marquette', 'Marquette', 'Big East', 'WI', 3, 'h', 1, 'Milwaukee'],
  ['Providence', 'Providence', 'Big East', 'RI', 2, 'h', 0, 'Providence'],
  ['Seton Hall', 'Seton Hall', 'Big East', 'NJ', 3, 's', 0, 'South Orange'],
  ["St. John's", "St. John's", 'Big East', 'NY', 4, 's', 0, 'Queens'],
  ['UConn', 'UConn', 'Big East', 'CT', 4, 'h', 1, 'Storrs'],
  ['Villanova', 'Villanova', 'Big East', 'PA', 3, 'm', 1, 'Villanova'],
  ['Xavier', 'Xavier', 'Big East', 'OH', 3, 's', 0, 'Cincinnati'],
  // Ivy
  ['Brown', 'Brown', 'Ivy League', 'RI', 3, 'm', 1, 'Providence'],
  ['Columbia', 'Columbia', 'Ivy League', 'NY', 3, 'm', 1, 'New York'],
  ['Cornell', 'Cornell', 'Ivy League', 'NY', 3, 'm', 1, 'Ithaca'],
  ['Dartmouth', 'Dartmouth', 'Ivy League', 'NH', 3, 'm', 1, 'Hanover'],
  ['Harvard', 'Harvard', 'Ivy League', 'MA', 3, 'm', 1, 'Cambridge'],
  ['Penn', 'Penn', 'Ivy League', 'PA', 3, 'm', 1, 'Philadelphia'],
  ['Princeton', 'Princeton', 'Ivy League', 'NJ', 3, 'm', 1, 'Princeton'],
  ['Yale', 'Yale', 'Ivy League', 'CT', 3, 'm', 1, 'New Haven'],
  // Patriot League
  ['American', 'American', 'Patriot League', 'DC', 3, 'h', 0, 'Washington'],
  ['Army', 'Army', 'Patriot League', 'NY', 3, 'h', 1, 'West Point'],
  ['Boston University', 'Boston U', 'Patriot League', 'MA', 4, 'h', 1, 'Boston'],
  ['Bucknell', 'Bucknell', 'Patriot League', 'PA', 2, 'h', 1, 'Lewisburg'],
  ['Colgate', 'Colgate', 'Patriot League', 'NY', 1, 'm', 0, 'Hamilton'],
  ['Holy Cross', 'Holy Cross', 'Patriot League', 'MA', 1, 'h', 0, 'Worcester'],
  ['Lafayette', 'Lafayette', 'Patriot League', 'PA', 1, 'h', 1, 'Easton'],
  ['Lehigh', 'Lehigh', 'Patriot League', 'PA', 3, 'h', 1, 'Bethlehem'],
  ['Loyola Maryland', 'Loyola MD', 'Patriot League', 'MD', 2, 's', 1, 'Baltimore'],
  ['Navy', 'Navy', 'Patriot League', 'MD', 3, 'h', 1, 'Annapolis'],
  // America East
  ['Albany', 'Albany', 'America East', 'NY', 3, 's', 0, 'Albany'],
  ['Binghamton', 'Binghamton', 'America East', 'NY', 3, 'h', 1, 'Binghamton'],
  ['Bryant', 'Bryant', 'America East', 'RI', 2, 's', 0, 'Smithfield'],
  ['New Hampshire', 'New Hampshire', 'America East', 'NH', 3, 's', 1, 'Durham'],
  ['UMBC', 'UMBC', 'America East', 'MD', 3, 's', 1, 'Baltimore'],
  ['UMass Lowell', 'UMass Lowell', 'America East', 'MA', 3, 's', 1, 'Lowell'],
  ['Vermont', 'Vermont', 'America East', 'VT', 3, 's', 1, 'Burlington'],
  ['NJIT', 'NJIT', 'America East', 'NJ', 3, 's', 1, 'Newark'],
  // CAA
  ['Campbell', 'Campbell', 'CAA', 'NC', 3, 's', 0, 'Buies Creek'],
  ['Charleston', 'Charleston', 'CAA', 'SC', 3, 's', 0, 'Charleston'],
  ['Drexel', 'Drexel', 'CAA', 'PA', 3, 's', 1, 'Philadelphia'],
  ['Elon', 'Elon', 'CAA', 'NC', 3, 'h', 1, 'Elon'],
  ['Hampton', 'Hampton', 'CAA', 'VA', 2, 's', 0, 'Hampton'],
  ['Hofstra', 'Hofstra', 'CAA', 'NY', 3, 's', 1, 'Hempstead'],
  ['Monmouth', 'Monmouth', 'CAA', 'NJ', 2, 's', 1, 'West Long Branch'],
  ['Northeastern', 'Northeastern', 'CAA', 'MA', 4, 'm', 1, 'Boston'],
  ['Stony Brook', 'Stony Brook', 'CAA', 'NY', 4, 'h', 1, 'Stony Brook'],
  ['Towson', 'Towson', 'CAA', 'MD', 4, 's', 0, 'Towson'],
  ['UNC Wilmington', 'UNCW', 'CAA', 'NC', 3, 's', 0, 'Wilmington'],
  ['William & Mary', 'William & Mary', 'CAA', 'VA', 3, 'm', 0, 'Williamsburg'],
  ['Delaware', 'Delaware', 'CAA', 'DE', 4, 's', 1, 'Newark'],
  ['Hartford', 'Hartford', 'CAA', 'CT', 2, 's', 1, 'West Hartford'],
  // Sun Belt
  ['Georgia State', 'Georgia St', 'Sun Belt', 'GA', 4, 's', 0, 'Atlanta'],
  ['Georgia Southern', 'Georgia Southern', 'Sun Belt', 'GA', 4, 's', 1, 'Statesboro'],
  ['James Madison', 'JMU', 'Sun Belt', 'VA', 4, 's', 1, 'Harrisonburg'],
  ['Kentucky', 'Kentucky', 'Sun Belt', 'KY', 4, 's', 1, 'Lexington'],
  ['Marshall', 'Marshall', 'Sun Belt', 'WV', 3, 's', 1, 'Huntington'],
  ['Old Dominion', 'Old Dominion', 'Sun Belt', 'VA', 4, 's', 1, 'Norfolk'],
  ['South Carolina', 'South Carolina', 'Sun Belt', 'SC', 4, 's', 1, 'Columbia'],
  ['Coastal Carolina', 'Coastal Carolina', 'Sun Belt', 'SC', 3, 's', 0, 'Conway'],
  ['App State', 'App State', 'Sun Belt', 'NC', 4, 's', 0, 'Boone'],
  ['UCF', 'UCF', 'Sun Belt', 'FL', 4, 's', 1, 'Orlando'],
  ['West Virginia', 'West Virginia', 'Sun Belt', 'WV', 4, 's', 1, 'Morgantown'],
  // American (AAC)
  ['Charlotte', 'Charlotte', 'American', 'NC', 4, 's', 1, 'Charlotte'],
  ['FIU', 'FIU', 'American', 'FL', 4, 's', 1, 'Miami'],
  ['Florida Atlantic', 'FAU', 'American', 'FL', 4, 's', 1, 'Boca Raton'],
  ['Memphis', 'Memphis', 'American', 'TN', 4, 's', 1, 'Memphis'],
  ['South Florida', 'USF', 'American', 'FL', 4, 's', 1, 'Tampa'],
  ['Temple', 'Temple', 'American', 'PA', 4, 's', 1, 'Philadelphia'],
  ['Tulsa', 'Tulsa', 'American', 'OK', 2, 's', 1, 'Tulsa'],
  ['UAB', 'UAB', 'American', 'AL', 4, 's', 1, 'Birmingham'],
  // Conference USA
  // Big West
  ['Cal Poly', 'Cal Poly', 'Big West', 'CA', 4, 'h', 1, 'San Luis Obispo'],
  ['CSUN', 'CSUN', 'Big West', 'CA', 4, 'a', 1, 'Northridge'],
  ['UC Davis', 'UC Davis', 'Big West', 'CA', 4, 'h', 1, 'Davis'],
  ['UC Irvine', 'UC Irvine', 'Big West', 'CA', 4, 'h', 1, 'Irvine'],
  ['UC Riverside', 'UC Riverside', 'Big West', 'CA', 4, 's', 1, 'Riverside'],
  ['UC Santa Barbara', 'UCSB', 'Big West', 'CA', 4, 'h', 1, 'Santa Barbara'],
  ['Cal State Fullerton', 'CSU Fullerton', 'Big West', 'CA', 4, 's', 1, 'Fullerton'],
  ['UC San Diego', 'UC San Diego', 'Big West', 'CA', 4, 'h', 1, 'La Jolla'],
  // WCC
  ['Gonzaga', 'Gonzaga', 'WCC', 'WA', 3, 'h', 1, 'Spokane'],
  ['Loyola Marymount', 'LMU', 'WCC', 'CA', 3, 's', 1, 'Los Angeles'],
  ['Pacific', 'Pacific', 'WCC', 'CA', 2, 's', 1, 'Stockton'],
  ['Portland', 'Portland', 'WCC', 'OR', 2, 'h', 1, 'Portland'],
  ["Saint Mary's", "Saint Mary's", 'WCC', 'CA', 2, 'h', 0, 'Moraga'],
  ['San Diego', 'San Diego', 'WCC', 'CA', 3, 'h', 1, 'San Diego'],
  ['San Francisco', 'San Francisco', 'WCC', 'CA', 3, 's', 0, 'San Francisco'],
  ['Santa Clara', 'Santa Clara', 'WCC', 'CA', 3, 'm', 1, 'Santa Clara'],
  ['Oregon State', 'Oregon St', 'WCC', 'OR', 4, 's', 1, 'Corvallis'],
  ['Seattle', 'Seattle U', 'WCC', 'WA', 3, 's', 1, 'Seattle'],
  // Missouri Valley
  ['Belmont', 'Belmont', 'Missouri Valley', 'TN', 3, 's', 0, 'Nashville'],
  ['Bradley', 'Bradley', 'Missouri Valley', 'IL', 3, 's', 1, 'Peoria'],
  ['Drake', 'Drake', 'Missouri Valley', 'IA', 2, 'h', 0, 'Des Moines'],
  ['Evansville', 'Evansville', 'Missouri Valley', 'IN', 2, 's', 1, 'Evansville'],
  ['Missouri State', 'Missouri St', 'Missouri Valley', 'MO', 4, 's', 0, 'Springfield'],
  ['Murray State', 'Murray St', 'Missouri Valley', 'KY', 3, 's', 1, 'Murray'],
  ['UIC', 'UIC', 'Missouri Valley', 'IL', 4, 's', 1, 'Chicago'],
  ['Valparaiso', 'Valparaiso', 'Missouri Valley', 'IN', 2, 's', 1, 'Valparaiso'],
  ['SIU Edwardsville', 'SIUE', 'Missouri Valley', 'IL', 3, 's', 1, 'Edwardsville'],
  ['Northern Illinois', 'NIU', 'Missouri Valley', 'IL', 4, 's', 1, 'DeKalb'],
  // Horizon League
  ['Cleveland State', 'Cleveland St', 'Horizon', 'OH', 3, 's', 1, 'Cleveland'],
  ['Detroit Mercy', 'Detroit Mercy', 'Horizon', 'MI', 2, 's', 1, 'Detroit'],
  ['Green Bay', 'Green Bay', 'Horizon', 'WI', 3, 's', 0, 'Green Bay'],
  ['Milwaukee', 'Milwaukee', 'Horizon', 'WI', 4, 's', 1, 'Milwaukee'],
  ['Northern Kentucky', 'NKU', 'Horizon', 'KY', 4, 's', 0, 'Highland Heights'],
  ['Oakland', 'Oakland', 'Horizon', 'MI', 4, 's', 1, 'Rochester'],
  ['Purdue Fort Wayne', 'Purdue FW', 'Horizon', 'IN', 3, 's', 1, 'Fort Wayne'],
  ['Robert Morris', 'Robert Morris', 'Horizon', 'PA', 3, 's', 1, 'Moon Township'],
  ['Wright State', 'Wright St', 'Horizon', 'OH', 3, 's', 1, 'Dayton'],
  ['Youngstown State', 'Youngstown St', 'Horizon', 'OH', 3, 's', 1, 'Youngstown'],
  // Summit League
  ['Denver', 'Denver', 'Summit League', 'CO', 3, 's', 1, 'Denver'],
  ['Oral Roberts', 'Oral Roberts', 'Summit League', 'OK', 2, 's', 1, 'Tulsa'],
  ['Omaha', 'Omaha', 'Summit League', 'NE', 3, 's', 0, 'Omaha'],
  ['St. Thomas', 'St. Thomas', 'Summit League', 'MN', 3, 's', 1, 'St. Paul'],
  ['Kansas City', 'Kansas City', 'Summit League', 'MO', 3, 's', 1, 'Kansas City'],
  ['Western Illinois', 'Western Illinois', 'Summit League', 'IL', 3, 'a', 0, 'Macomb'],
  // MAAC
  ['Canisius', 'Canisius', 'MAAC', 'NY', 2, 's', 0, 'Buffalo'],
  ['Fairfield', 'Fairfield', 'MAAC', 'CT', 2, 'h', 1, 'Fairfield'],
  ['Iona', 'Iona', 'MAAC', 'NY', 2, 's', 0, 'New Rochelle'],
  ['Manhattan', 'Manhattan', 'MAAC', 'NY', 2, 's', 1, 'Riverdale'],
  ['Marist', 'Marist', 'MAAC', 'NY', 3, 's', 0, 'Poughkeepsie'],
  ["Mount St. Mary's", "Mount St. Mary's", 'MAAC', 'MD', 2, 's', 0, 'Emmitsburg'],
  ['Niagara', 'Niagara', 'MAAC', 'NY', 2, 's', 0, 'Niagara'],
  ['Quinnipiac', 'Quinnipiac', 'MAAC', 'CT', 3, 's', 1, 'Hamden'],
  ['Rider', 'Rider', 'MAAC', 'NJ', 2, 's', 0, 'Lawrenceville'],
  ['Sacred Heart', 'Sacred Heart', 'MAAC', 'CT', 3, 's', 1, 'Fairfield'],
  ["Saint Peter's", "Saint Peter's", 'MAAC', 'NJ', 2, 'a', 0, 'Jersey City'],
  ['Siena', 'Siena', 'MAAC', 'NY', 2, 's', 0, 'Loudonville'],
  ['Merrimack', 'Merrimack', 'MAAC', 'MA', 3, 's', 1, 'North Andover'],
  // Northeast Conference (NEC)
  ['Central Connecticut', 'CCSU', 'NEC', 'CT', 3, 'a', 1, 'New Britain'],
  ['Fairleigh Dickinson', 'FDU', 'NEC', 'NJ', 2, 's', 0, 'Teaneck'],
  ['LIU', 'LIU', 'NEC', 'NY', 3, 'a', 0, 'Brookville'],
  ['Saint Francis', 'Saint Francis PA', 'NEC', 'PA', 1, 's', 0, 'Loretto'],
  ['Stonehill', 'Stonehill', 'NEC', 'MA', 2, 's', 0, 'Easton'],
  ['Wagner', 'Wagner', 'NEC', 'NY', 2, 's', 0, 'Staten Island'],
  ['Le Moyne', 'Le Moyne', 'NEC', 'NY', 2, 's', 0, 'Syracuse'],
  ['Chicago State', 'Chicago St', 'NEC', 'IL', 2, 'a', 0, 'Chicago'],
  // SoCon
  ['Furman', 'Furman', 'SoCon', 'SC', 2, 'h', 1, 'Greenville'],
  ['Mercer', 'Mercer', 'SoCon', 'GA', 3, 's', 1, 'Macon'],
  ['ETSU', 'ETSU', 'SoCon', 'TN', 4, 's', 1, 'Johnson City'],
  ['UNC Greensboro', 'UNCG', 'SoCon', 'NC', 4, 's', 1, 'Greensboro'],
  ['VMI', 'VMI', 'SoCon', 'VA', 1, 's', 1, 'Lexington'],
  ['The Citadel', 'The Citadel', 'SoCon', 'SC', 2, 's', 1, 'Charleston'],
  ['Wofford', 'Wofford', 'SoCon', 'SC', 1, 'h', 0, 'Spartanburg'],
  ['Western Carolina', 'Western Carolina', 'SoCon', 'NC', 3, 's', 1, 'Cullowhee'],
  // Big South
  ['High Point', 'High Point', 'Big South', 'NC', 3, 's', 1, 'High Point'],
  ['Longwood', 'Longwood', 'Big South', 'VA', 3, 's', 0, 'Farmville'],
  ['Radford', 'Radford', 'Big South', 'VA', 3, 's', 0, 'Radford'],
  ['UNC Asheville', 'UNC Asheville', 'Big South', 'NC', 2, 's', 0, 'Asheville'],
  ['Presbyterian', 'Presbyterian', 'Big South', 'SC', 1, 's', 0, 'Clinton'],
  ['Winthrop', 'Winthrop', 'Big South', 'SC', 3, 's', 0, 'Rock Hill'],
  ['Gardner-Webb', 'Gardner-Webb', 'Big South', 'NC', 2, 's', 1, 'Boiling Springs'],
  ['USC Upstate', 'USC Upstate', 'Big South', 'SC', 3, 's', 0, 'Spartanburg'],
  ['Charleston Southern', 'Charleston Southern', 'Big South', 'SC', 2, 'a', 1, 'Charleston'],
  // ASUN
  ['Lipscomb', 'Lipscomb', 'ASUN', 'TN', 3, 's', 1, 'Nashville'],
  ['North Alabama', 'North Alabama', 'ASUN', 'AL', 3, 's', 1, 'Florence'],
  ['Jacksonville', 'Jacksonville', 'ASUN', 'FL', 2, 's', 1, 'Jacksonville'],
  ['Stetson', 'Stetson', 'ASUN', 'FL', 2, 's', 1, 'DeLand'],
  ['Bellarmine', 'Bellarmine', 'ASUN', 'KY', 2, 's', 1, 'Louisville'],
  ['Austin Peay', 'Austin Peay', 'ASUN', 'TN', 3, 'a', 1, 'Clarksville'],
  ['Central Arkansas', 'Central Arkansas', 'ASUN', 'AR', 3, 'a', 1, 'Conway'],
  // WAC / independents / other D1
  ['Grand Canyon', 'Grand Canyon', 'WAC', 'AZ', 4, 's', 1, 'Phoenix'],
  ['Seattle U', 'Seattle U', null, 'WA', 3, 's', 1, 'Seattle'],
  ['UT Rio Grande Valley', 'UTRGV', 'WAC', 'TX', 4, 'a', 1, 'Edinburg'],
  ['Utah Tech', 'Utah Tech', 'WAC', 'UT', 3, 'a', 1, 'St. George'],
  ['California Baptist', 'Cal Baptist', 'WAC', 'CA', 3, 's', 1, 'Riverside'],
  ['Air Force', 'Air Force', 'MPSF', 'CO', 3, 'h', 1, 'Colorado Springs'],
  ['Incarnate Word', 'Incarnate Word', 'Southland', 'TX', 3, 'a', 1, 'San Antonio'],
  ['Houston Christian', 'Houston Christian', 'Southland', 'TX', 1, 's', 0, 'Houston'],
  // Atlantic 10
  ['Davidson', 'Davidson', 'Atlantic 10', 'NC', 1, 'm', 0, 'Davidson'],
  ['Dayton', 'Dayton', 'Atlantic 10', 'OH', 3, 's', 1, 'Dayton'],
  ['Duquesne', 'Duquesne', 'Atlantic 10', 'PA', 3, 's', 1, 'Pittsburgh'],
  ['Fordham', 'Fordham', 'Atlantic 10', 'NY', 3, 'h', 1, 'Bronx'],
  ['George Mason', 'George Mason', 'Atlantic 10', 'VA', 4, 's', 1, 'Fairfax'],
  ['George Washington', 'George Washington', 'Atlantic 10', 'DC', 3, 'h', 1, 'Washington'],
  ['La Salle', 'La Salle', 'Atlantic 10', 'PA', 2, 's', 0, 'Philadelphia'],
  ['Rhode Island', 'Rhode Island', 'Atlantic 10', 'RI', 4, 's', 1, 'Kingston'],
  ["Saint Joseph's (PA)", "Saint Joseph's PA", 'Atlantic 10', 'PA', 3, 's', 0, 'Philadelphia'],
  ['Saint Louis', 'Saint Louis', 'Atlantic 10', 'MO', 3, 'h', 1, 'St. Louis'],
  ['UMass', 'UMass', 'Atlantic 10', 'MA', 4, 's', 1, 'Amherst'],
  ['VCU', 'VCU', 'Atlantic 10', 'VA', 4, 's', 1, 'Richmond'],
  ['Loyola Chicago', 'Loyola Chicago', 'Atlantic 10', 'IL', 3, 'h', 0, 'Chicago'],
  ['Richmond', 'Richmond', 'Atlantic 10', 'VA', 2, 'm', 0, 'Richmond'],
  ['St. Bonaventure', 'St. Bonaventure', 'Atlantic 10', 'NY', 1, 's', 0, 'St. Bonaventure'],
]

// ─── D2 ────────────────────────────────────────────────────────────────────
const D2: Row[] = [
  ['Colorado School of Mines', 'Mines', 'RMAC', 'CO', 2, 'h', 1, 'Golden'],
  ['Colorado Mesa', 'Colorado Mesa', 'RMAC', 'CO', 3, 'a', 1, 'Grand Junction'],
  ['Colorado Springs', 'UCCS', 'RMAC', 'CO', 3, 's', 1, 'Colorado Springs'],
  ['Regis', 'Regis', 'RMAC', 'CO', 2, 's', 0, 'Denver'],
  ['CSU Pueblo', 'CSU Pueblo', 'RMAC', 'CO', 2, 'a', 1, 'Pueblo'],
  ['Metro State Denver', 'MSU Denver', 'RMAC', 'CO', 4, 'a', 1, 'Denver'],
  ['Fort Lewis', 'Fort Lewis', 'RMAC', 'CO', 2, 'a', 0, 'Durango'],
  ['Westminster', 'Westminster UT', 'RMAC', 'UT', 1, 's', 0, 'Salt Lake City'],
  ['Cal Poly Pomona', 'Cal Poly Pomona', 'CCAA', 'CA', 4, 's', 1, 'Pomona'],
  ['Cal State LA', 'Cal State LA', 'CCAA', 'CA', 4, 'a', 1, 'Los Angeles'],
  ['Cal State San Bernardino', 'CSUSB', 'CCAA', 'CA', 4, 'a', 0, 'San Bernardino'],
  ['Chico State', 'Chico St', 'CCAA', 'CA', 4, 's', 1, 'Chico'],
  ['Cal State Dominguez Hills', 'CSUDH', 'CCAA', 'CA', 3, 'a', 0, 'Carson'],
  ['Cal State East Bay', 'Cal State East Bay', 'CCAA', 'CA', 3, 'a', 0, 'Hayward'],
  ['Sonoma State', 'Sonoma St', 'CCAA', 'CA', 3, 's', 0, 'Rohnert Park'],
  ['Stanislaus State', 'Stanislaus St', 'CCAA', 'CA', 3, 'a', 0, 'Turlock'],
  ['UC San Diego', 'UCSD (former D2)', 'CCAA', 'CA', 4, 'h', 1, 'La Jolla'],
  ['Point Loma', 'Point Loma', 'PacWest', 'CA', 2, 's', 1, 'San Diego'],
  ['Azusa Pacific', 'Azusa Pacific', 'PacWest', 'CA', 3, 's', 1, 'Azusa'],
  ['Biola', 'Biola', 'PacWest', 'CA', 2, 's', 1, 'La Mirada'],
  ['Fresno Pacific', 'Fresno Pacific', 'PacWest', 'CA', 2, 'a', 0, 'Fresno'],
  ['Hawaii Pacific', 'Hawaii Pacific', 'PacWest', 'HI', 2, 'a', 0, 'Honolulu'],
  ['Concordia Irvine', 'Concordia Irvine', 'PacWest', 'CA', 2, 's', 0, 'Irvine'],
  ['Seattle Pacific', 'Seattle Pacific', 'GNAC', 'WA', 2, 's', 1, 'Seattle'],
  ['Western Washington', 'Western Washington', 'GNAC', 'WA', 4, 's', 0, 'Bellingham'],
  ['Simon Fraser', 'Simon Fraser', 'GNAC', 'WA', 4, 's', 1, 'Burnaby'],
  ['Saint Martin’s', "Saint Martin's", 'GNAC', 'WA', 1, 's', 1, 'Lacey'],
  ['Northwest Nazarene', 'Northwest Nazarene', 'GNAC', 'ID', 1, 's', 1, 'Nampa'],
  ['Charleston (WV)', 'Charleston WV', 'MEC', 'WV', 1, 'a', 1, 'Charleston'],
  ['West Virginia Wesleyan', 'WV Wesleyan', 'MEC', 'WV', 1, 's', 1, 'Buckhannon'],
  ['Wheeling', 'Wheeling', 'MEC', 'WV', 1, 'a', 0, 'Wheeling'],
  ['Fairmont State', 'Fairmont St', 'MEC', 'WV', 2, 'a', 1, 'Fairmont'],
  ['Lynn', 'Lynn', 'Sunshine State', 'FL', 1, 's', 0, 'Boca Raton'],
  ['Tampa', 'Tampa', 'Sunshine State', 'FL', 3, 's', 1, 'Tampa'],
  ['Rollins', 'Rollins', 'Sunshine State', 'FL', 2, 'h', 0, 'Winter Park'],
  ['Barry', 'Barry', 'Sunshine State', 'FL', 3, 'a', 0, 'Miami Shores'],
  ['Nova Southeastern', 'Nova Southeastern', 'Sunshine State', 'FL', 4, 's', 1, 'Fort Lauderdale'],
  ['Florida Tech', 'Florida Tech', 'Sunshine State', 'FL', 2, 's', 1, 'Melbourne'],
  ['Embry-Riddle', 'Embry-Riddle', 'Sunshine State', 'FL', 3, 's', 1, 'Daytona Beach'],
  ['Palm Beach Atlantic', 'PBA', 'Sunshine State', 'FL', 2, 's', 0, 'West Palm Beach'],
  ['Lee', 'Lee', 'Gulf South', 'TN', 3, 's', 0, 'Cleveland'],
  ['Union', 'Union TN', 'Gulf South', 'TN', 2, 's', 1, 'Jackson'],
  ['Montevallo', 'Montevallo', 'Gulf South', 'AL', 2, 's', 0, 'Montevallo'],
  ['West Florida', 'West Florida', 'Gulf South', 'FL', 3, 's', 1, 'Pensacola'],
  ['Wingate', 'Wingate', 'South Atlantic', 'NC', 2, 's', 1, 'Wingate'],
  ['Lenoir-Rhyne', 'Lenoir-Rhyne', 'South Atlantic', 'NC', 2, 's', 0, 'Hickory'],
  ['Catawba', 'Catawba', 'South Atlantic', 'NC', 1, 's', 0, 'Salisbury'],
  ['Queens (NC)', 'Queens NC', 'South Atlantic', 'NC', 2, 's', 0, 'Charlotte'],
  ['Anderson (SC)', 'Anderson SC', 'South Atlantic', 'SC', 2, 's', 0, 'Anderson'],
  ['Lincoln Memorial', 'Lincoln Memorial', 'South Atlantic', 'TN', 3, 's', 1, 'Harrogate'],
  ['Tusculum', 'Tusculum', 'South Atlantic', 'TN', 1, 'a', 0, 'Greeneville'],
  ['Franklin Pierce', 'Franklin Pierce', 'Northeast-10', 'NH', 1, 'a', 0, 'Rindge'],
  ['Southern New Hampshire', 'SNHU', 'Northeast-10', 'NH', 3, 's', 1, 'Manchester'],
  ['Saint Anselm', 'Saint Anselm', 'Northeast-10', 'NH', 2, 's', 0, 'Manchester'],
  ['Bentley', 'Bentley', 'Northeast-10', 'MA', 2, 'h', 0, 'Waltham'],
  ['Assumption', 'Assumption', 'Northeast-10', 'MA', 2, 's', 0, 'Worcester'],
  ['American International', 'AIC', 'Northeast-10', 'MA', 2, 'a', 1, 'Springfield'],
  ['Adelphi', 'Adelphi', 'Northeast-10', 'NY', 3, 's', 0, 'Garden City'],
  ['Pace', 'Pace', 'Northeast-10', 'NY', 3, 's', 1, 'Pleasantville'],
  ['Saint Rose', 'Saint Rose', 'Northeast-10', 'NY', 2, 's', 0, 'Albany'],
  ['New Haven', 'New Haven', 'Northeast-10', 'CT', 2, 's', 1, 'West Haven'],
  ['Southern Connecticut', 'Southern Connecticut', 'Northeast-10', 'CT', 3, 'a', 0, 'New Haven'],
  ['Millersville', 'Millersville', 'PSAC', 'PA', 3, 's', 1, 'Millersville'],
  ['West Chester', 'West Chester', 'PSAC', 'PA', 4, 's', 0, 'West Chester'],
  ['Bloomsburg', 'Bloomsburg', 'PSAC', 'PA', 3, 'a', 0, 'Bloomsburg'],
  ['Shippensburg', 'Shippensburg', 'PSAC', 'PA', 3, 'a', 0, 'Shippensburg'],
  ['Kutztown', 'Kutztown', 'PSAC', 'PA', 3, 'a', 0, 'Kutztown'],
  ['Mercyhurst', 'Mercyhurst', 'PSAC', 'PA', 2, 's', 0, 'Erie'],
  ['Slippery Rock', 'Slippery Rock', 'PSAC', 'PA', 3, 'a', 0, 'Slippery Rock'],
  ['Seton Hill', 'Seton Hill', 'PSAC', 'PA', 1, 's', 0, 'Greensburg'],
  ['Dominican (NY)', 'Dominican NY', 'CACC', 'NY', 1, 'a', 0, 'Orangeburg'],
  ['Post', 'Post', 'CACC', 'CT', 1, 'a', 0, 'Waterbury'],
  ['Bridgeport', 'Bridgeport', 'CACC', 'CT', 2, 'a', 1, 'Bridgeport'],
  ['Georgian Court', 'Georgian Court', 'CACC', 'NJ', 1, 'a', 0, 'Lakewood'],
  ['Molloy', 'Molloy', 'ECC', 'NY', 2, 's', 0, 'Rockville Centre'],
  ['Roberts Wesleyan', 'Roberts Wesleyan', 'ECC', 'NY', 1, 's', 0, 'Rochester'],
  ['Daemen', 'Daemen', 'ECC', 'NY', 1, 's', 0, 'Amherst'],
  ['Lewis', 'Lewis', 'GLVC', 'IL', 2, 's', 1, 'Romeoville'],
  ['Maryville', 'Maryville', 'GLVC', 'MO', 2, 's', 0, 'St. Louis'],
  ['Rockhurst', 'Rockhurst', 'GLVC', 'MO', 1, 's', 0, 'Kansas City'],
  ['Missouri S&T', 'Missouri S&T', 'GLVC', 'MO', 3, 's', 1, 'Rolla'],
  ['Drury', 'Drury', 'GLVC', 'MO', 2, 's', 1, 'Springfield'],
  ['McKendree', 'McKendree', 'GLVC', 'IL', 1, 's', 0, 'Lebanon'],
  ['Indianapolis', 'UIndy', 'GLVC', 'IN', 3, 's', 1, 'Indianapolis'],
  ['Southern Indiana', 'Southern Indiana', 'OVC', 'IN', 3, 'a', 1, 'Evansville'],
  ['Ashland', 'Ashland', 'GMAC', 'OH', 2, 's', 1, 'Ashland'],
  ['Findlay', 'Findlay', 'GMAC', 'OH', 2, 's', 0, 'Findlay'],
  ['Malone', 'Malone', 'GMAC', 'OH', 1, 's', 0, 'Canton'],
  ['Walsh', 'Walsh', 'GMAC', 'OH', 1, 's', 0, 'North Canton'],
  ['Tiffin', 'Tiffin', 'GMAC', 'OH', 2, 'a', 0, 'Tiffin'],
  ['Grand Valley State', 'Grand Valley St', 'GLIAC', 'MI', 4, 's', 0, 'Allendale'],
  ['Davenport', 'Davenport', 'GLIAC', 'MI', 2, 's', 0, 'Grand Rapids'],
  ['Northern Michigan', 'Northern Michigan', 'GLIAC', 'MI', 3, 'a', 1, 'Marquette'],
  ['Parkside', 'Wisconsin-Parkside', 'GLIAC', 'WI', 2, 'a', 0, 'Kenosha'],
  ['Minnesota State Mankato', 'MSU Mankato', 'NSIC', 'MN', 4, 's', 1, 'Mankato'],
  ['Minnesota Duluth', 'Minnesota Duluth', 'NSIC', 'MN', 3, 's', 1, 'Duluth'],
  ['Sioux Falls', 'Sioux Falls', 'NSIC', 'SD', 1, 's', 0, 'Sioux Falls'],
  ['Midwestern State', 'Midwestern St', 'Lone Star', 'TX', 3, 'a', 1, 'Wichita Falls'],
  ['St. Edward’s', "St. Edward's", 'Lone Star', 'TX', 2, 's', 0, 'Austin'],
  ['St. Mary’s (TX)', "St. Mary's TX", 'Lone Star', 'TX', 2, 's', 1, 'San Antonio'],
  ['Dallas Baptist', 'Dallas Baptist', 'Lone Star', 'TX', 2, 's', 0, 'Dallas'],
  ['UT Tyler', 'UT Tyler', 'Lone Star', 'TX', 3, 'a', 1, 'Tyler'],
  ['Colorado Christian', 'Colorado Christian', 'RMAC', 'CO', 2, 's', 0, 'Lakewood'],
  ['Black Hills State', 'Black Hills St', 'RMAC', 'SD', 1, 'a', 0, 'Spearfish'],
  // Peach Belt
  ['Columbus State', 'Columbus St', 'Peach Belt', 'GA', 3, 'a', 1, 'Columbus'],
  ['Flagler', 'Flagler', 'Peach Belt', 'FL', 2, 's', 0, 'St. Augustine'],
  ['Georgia College', 'Georgia College', 'Peach Belt', 'GA', 3, 's', 0, 'Milledgeville'],
  ['Young Harris', 'Young Harris', 'Peach Belt', 'GA', 1, 's', 0, 'Young Harris'],
  ['Lander', 'Lander', 'Peach Belt', 'SC', 2, 'a', 0, 'Greenwood'],
  ['USC Aiken', 'USC Aiken', 'Peach Belt', 'SC', 2, 's', 0, 'Aiken'],
  ['Augusta', 'Augusta', 'Peach Belt', 'GA', 4, 's', 0, 'Augusta'],
  ['Clayton State', 'Clayton St', 'Peach Belt', 'GA', 3, 'a', 0, 'Morrow'],
  // Conference Carolinas
  ['Belmont Abbey', 'Belmont Abbey', 'Conference Carolinas', 'NC', 1, 's', 0, 'Belmont'],
  ['Emmanuel (GA)', 'Emmanuel GA', 'Conference Carolinas', 'GA', 1, 'a', 0, 'Franklin Springs'],
  ['Erskine', 'Erskine', 'Conference Carolinas', 'SC', 1, 's', 0, 'Due West'],
  ['King (TN)', 'King TN', 'Conference Carolinas', 'TN', 1, 's', 0, 'Bristol'],
  ['Limestone', 'Limestone', 'Conference Carolinas', 'SC', 1, 'a', 0, 'Gaffney'],
  ['Mount Olive', 'Mount Olive', 'Conference Carolinas', 'NC', 1, 'a', 0, 'Mount Olive'],
  ['Southern Wesleyan', 'Southern Wesleyan', 'Conference Carolinas', 'SC', 1, 'a', 0, 'Central'],
  ['Chowan', 'Chowan', 'Conference Carolinas', 'NC', 1, 'a', 0, 'Murfreesboro'],
  ['UNC Pembroke', 'UNC Pembroke', 'Conference Carolinas', 'NC', 3, 'a', 0, 'Pembroke'],
  ['Barton (NC)', 'Barton NC', 'Conference Carolinas', 'NC', 1, 's', 0, 'Wilson'],
  ['Converse', 'Converse', 'Conference Carolinas', 'SC', 1, 's', 0, 'Spartanburg'],
  // More Northeast-10 / East Coast D2
  ['Saint Michael’s', "Saint Michael's", 'Northeast-10', 'VT', 1, 's', 0, 'Colchester'],
  ['Caldwell', 'Caldwell', 'CACC', 'NJ', 1, 'a', 0, 'Caldwell'],
  ['Felician', 'Felician', 'CACC', 'NJ', 1, 'a', 0, 'Lodi'],
  ['Holy Family', 'Holy Family', 'CACC', 'PA', 1, 'a', 0, 'Philadelphia'],
  ['Jefferson', 'Jefferson', 'CACC', 'PA', 3, 's', 1, 'Philadelphia'],
  ['Wilmington (DE)', 'Wilmington DE', 'CACC', 'DE', 3, 'a', 0, 'New Castle'],
  ['Goldey-Beacom', 'Goldey-Beacom', 'CACC', 'DE', 1, 'a', 0, 'Wilmington'],
  // More PSAC
  ['East Stroudsburg', 'East Stroudsburg', 'PSAC', 'PA', 3, 'a', 0, 'East Stroudsburg'],
  ['Lock Haven', 'Lock Haven', 'PSAC', 'PA', 2, 'a', 0, 'Lock Haven'],
  ['Mansfield', 'Mansfield', 'PSAC', 'PA', 1, 'a', 0, 'Mansfield'],
  ['Gannon', 'Gannon', 'PSAC', 'PA', 2, 's', 1, 'Erie'],
  ['Edinboro', 'Edinboro', 'PSAC', 'PA', 2, 'a', 0, 'Edinboro'],
  ['California (PA)', 'PennWest California', 'PSAC', 'PA', 2, 'a', 0, 'California'],
  // More Lone Star / Heartland (South Central)
  ['Angelo State', 'Angelo St', 'Lone Star', 'TX', 3, 'a', 1, 'San Angelo'],
  ['West Texas A&M', 'West Texas A&M', 'Lone Star', 'TX', 3, 'a', 1, 'Canyon'],
  ['Lubbock Christian', 'Lubbock Christian', 'Lone Star', 'TX', 1, 'a', 0, 'Lubbock'],
  ['Oklahoma Christian', 'Oklahoma Christian', 'Lone Star', 'OK', 1, 's', 1, 'Oklahoma City'],
  ['Rogers State', 'Rogers St', 'MIAA (D2)', 'OK', 2, 'a', 0, 'Claremore'],
  ['Newman', 'Newman', 'MIAA (D2)', 'KS', 1, 'a', 0, 'Wichita'],
  ['Central Missouri', 'Central Missouri', 'MIAA (D2)', 'MO', 3, 's', 1, 'Warrensburg'],
  ['Fort Hays State', 'Fort Hays St', 'MIAA (D2)', 'KS', 3, 'a', 1, 'Hays'],
  ['Missouri Southern', 'Missouri Southern', 'MIAA (D2)', 'MO', 3, 'a', 0, 'Joplin'],
  // More Sunshine State / Southeast D2
  ['Saint Leo', 'Saint Leo', 'Sunshine State', 'FL', 2, 's', 0, 'Saint Leo'],
  ['Florida Southern', 'Florida Southern', 'Sunshine State', 'FL', 2, 's', 1, 'Lakeland'],
  // Gulf South (more)
  ['Christian Brothers', 'Christian Brothers', 'Gulf South', 'TN', 1, 's', 1, 'Memphis'],
  ['Alabama-Huntsville', 'UAH', 'Gulf South', 'AL', 3, 's', 1, 'Huntsville'],
  ['Mississippi College', 'Mississippi College', 'Gulf South', 'MS', 2, 's', 0, 'Clinton'],
  ['Delta State', 'Delta St', 'Gulf South', 'MS', 2, 'a', 0, 'Cleveland'],
  ['Shorter', 'Shorter', 'Gulf South', 'GA', 1, 'a', 0, 'Rome'],
  ['Valdosta State', 'Valdosta St', 'Gulf South', 'GA', 4, 'a', 0, 'Valdosta'],
  ['West Alabama', 'West Alabama', 'Gulf South', 'AL', 2, 'a', 0, 'Livingston'],
  // GLIAC / GMAC (more)
  ['Purdue Northwest', 'Purdue Northwest', 'GLIAC', 'IN', 3, 's', 1, 'Hammond'],
  ['Saginaw Valley State', 'Saginaw Valley St', 'GLIAC', 'MI', 3, 'a', 1, 'University Center'],
  ['Wayne State (MI)', 'Wayne State MI', 'GLIAC', 'MI', 4, 's', 1, 'Detroit'],
  ['Lake Erie', 'Lake Erie', 'GMAC', 'OH', 1, 'a', 0, 'Painesville'],
  ['Cedarville', 'Cedarville', 'GMAC', 'OH', 2, 's', 1, 'Cedarville'],
  ['Kentucky Wesleyan', 'Kentucky Wesleyan', 'GMAC', 'KY', 1, 'a', 0, 'Owensboro'],
  ['Trevecca Nazarene', 'Trevecca', 'GMAC', 'TN', 2, 's', 0, 'Nashville'],
  // Mountain East (more)
  ['Concord', 'Concord', 'Mountain East', 'WV', 1, 'a', 0, 'Athens'],
  ['Davis & Elkins', 'Davis & Elkins', 'Mountain East', 'WV', 1, 'a', 0, 'Elkins'],
  ['Glenville State', 'Glenville St', 'Mountain East', 'WV', 1, 'a', 0, 'Glenville'],
  ['Frostburg State', 'Frostburg St', 'Mountain East', 'MD', 2, 'a', 1, 'Frostburg'],
  // Great Lakes Valley (more)
  ['Truman State', 'Truman St', 'GLVC', 'MO', 3, 'h', 0, 'Kirksville'],
  ['Illinois Springfield', 'Illinois Springfield', 'GLVC', 'IL', 2, 's', 0, 'Springfield'],
  ['Quincy', 'Quincy', 'GLVC', 'IL', 1, 's', 0, 'Quincy'],
  ['William Jewell', 'William Jewell', 'GLVC', 'MO', 1, 's', 0, 'Liberty'],
  // South Atlantic (more)
  ['Carson-Newman', 'Carson-Newman', 'South Atlantic', 'TN', 1, 's', 0, 'Jefferson City'],
  ['Coker', 'Coker', 'South Atlantic', 'SC', 1, 'a', 0, 'Hartsville'],
  ['Newberry', 'Newberry', 'South Atlantic', 'SC', 1, 'a', 0, 'Newberry'],
  ['Mars Hill', 'Mars Hill', 'South Atlantic', 'NC', 1, 'a', 0, 'Mars Hill'],
  ['Emory & Henry', 'Emory & Henry', 'South Atlantic', 'VA', 1, 's', 0, 'Emory'],
]

// ─── D3 ────────────────────────────────────────────────────────────────────
const D3: Row[] = [
  // NESCAC
  ['Amherst', 'Amherst', 'NESCAC', 'MA', 1, 'm', 0, 'Amherst'],
  ['Bates', 'Bates', 'NESCAC', 'ME', 1, 'h', 0, 'Lewiston'],
  ['Bowdoin', 'Bowdoin', 'NESCAC', 'ME', 1, 'm', 0, 'Brunswick'],
  ['Colby', 'Colby', 'NESCAC', 'ME', 1, 'm', 0, 'Waterville'],
  ['Connecticut College', 'Conn College', 'NESCAC', 'CT', 1, 'h', 0, 'New London'],
  ['Hamilton', 'Hamilton', 'NESCAC', 'NY', 1, 'm', 0, 'Clinton'],
  ['Middlebury', 'Middlebury', 'NESCAC', 'VT', 2, 'm', 0, 'Middlebury'],
  ['Trinity (CT)', 'Trinity CT', 'NESCAC', 'CT', 1, 'h', 1, 'Hartford'],
  ['Tufts', 'Tufts', 'NESCAC', 'MA', 3, 'm', 1, 'Medford'],
  ['Wesleyan', 'Wesleyan', 'NESCAC', 'CT', 1, 'm', 0, 'Middletown'],
  ['Williams', 'Williams', 'NESCAC', 'MA', 1, 'm', 0, 'Williamstown'],
  // UAA
  ['Brandeis', 'Brandeis', 'UAA', 'MA', 3, 'h', 0, 'Waltham'],
  ['Carnegie Mellon', 'Carnegie Mellon', 'UAA', 'PA', 3, 'm', 1, 'Pittsburgh'],
  ['Case Western Reserve', 'Case Western', 'UAA', 'OH', 3, 'm', 1, 'Cleveland'],
  ['University of Chicago', 'UChicago', 'UAA', 'IL', 3, 'm', 0, 'Chicago'],
  ['Emory', 'Emory', 'UAA', 'GA', 3, 'm', 0, 'Atlanta'],
  ['NYU', 'NYU', 'UAA', 'NY', 4, 'm', 1, 'New York'],
  ['Rochester', 'Rochester', 'UAA', 'NY', 3, 'm', 1, 'Rochester'],
  ['Washington U. St. Louis', 'WashU', 'UAA', 'MO', 3, 'm', 1, 'St. Louis'],
  // Liberty League
  ['St. Lawrence', 'St. Lawrence', 'Liberty League', 'NY', 2, 's', 0, 'Canton'],
  ['RPI', 'RPI', 'Liberty League', 'NY', 3, 'h', 1, 'Troy'],
  ['Union (NY)', 'Union NY', 'Liberty League', 'NY', 1, 'h', 1, 'Schenectady'],
  ['Skidmore', 'Skidmore', 'Liberty League', 'NY', 2, 'h', 0, 'Saratoga Springs'],
  ['Vassar', 'Vassar', 'Liberty League', 'NY', 2, 'm', 0, 'Poughkeepsie'],
  ['Bard', 'Bard', 'Liberty League', 'NY', 2, 'h', 0, 'Annandale-on-Hudson'],
  ['Clarkson', 'Clarkson', 'Liberty League', 'NY', 2, 's', 1, 'Potsdam'],
  ['Ithaca', 'Ithaca', 'Liberty League', 'NY', 3, 's', 1, 'Ithaca'],
  ['Rochester Tech', 'RIT', 'Liberty League', 'NY', 4, 's', 1, 'Rochester'],
  ['Hobart', 'Hobart', 'Liberty League', 'NY', 1, 'h', 0, 'Geneva'],
  // NEWMAC
  ['MIT', 'MIT', 'NEWMAC', 'MA', 3, 'm', 1, 'Cambridge'],
  ['WPI', 'WPI', 'NEWMAC', 'MA', 2, 'h', 1, 'Worcester'],
  ['Clark University', 'Clark', 'NEWMAC', 'MA', 2, 'h', 0, 'Worcester'],
  ['Babson', 'Babson', 'NEWMAC', 'MA', 2, 'h', 0, 'Wellesley'],
  ['Springfield', 'Springfield', 'NEWMAC', 'MA', 2, 's', 1, 'Springfield'],
  ['Coast Guard', 'Coast Guard', 'NEWMAC', 'CT', 1, 'h', 1, 'New London'],
  ['Wheaton (MA)', 'Wheaton MA', 'NEWMAC', 'MA', 1, 's', 0, 'Norton'],
  ['Emerson', 'Emerson', 'NEWMAC', 'MA', 2, 'h', 0, 'Boston'],
  // Centennial
  ['Johns Hopkins', 'Johns Hopkins', 'Centennial', 'MD', 3, 'm', 1, 'Baltimore'],
  ['Swarthmore', 'Swarthmore', 'Centennial', 'PA', 1, 'm', 1, 'Swarthmore'],
  ['Haverford', 'Haverford', 'Centennial', 'PA', 1, 'm', 0, 'Haverford'],
  ['Gettysburg', 'Gettysburg', 'Centennial', 'PA', 1, 'h', 0, 'Gettysburg'],
  ['Dickinson', 'Dickinson', 'Centennial', 'PA', 1, 'h', 0, 'Carlisle'],
  ['Franklin & Marshall', 'F&M', 'Centennial', 'PA', 1, 'h', 0, 'Lancaster'],
  ['Muhlenberg', 'Muhlenberg', 'Centennial', 'PA', 1, 'h', 0, 'Allentown'],
  ['Ursinus', 'Ursinus', 'Centennial', 'PA', 1, 's', 0, 'Collegeville'],
  ['Washington College', 'Washington College', 'Centennial', 'MD', 1, 's', 0, 'Chestertown'],
  ['McDaniel', 'McDaniel', 'Centennial', 'MD', 1, 's', 0, 'Westminster'],
  // SCIAC
  ['Pomona-Pitzer', 'Pomona-Pitzer', 'SCIAC', 'CA', 1, 'm', 0, 'Claremont'],
  ['Claremont-Mudd-Scripps', 'CMS', 'SCIAC', 'CA', 1, 'm', 1, 'Claremont'],
  ['Occidental', 'Occidental', 'SCIAC', 'CA', 1, 'h', 0, 'Los Angeles'],
  ['Redlands', 'Redlands', 'SCIAC', 'CA', 2, 's', 0, 'Redlands'],
  ['Whittier', 'Whittier', 'SCIAC', 'CA', 1, 's', 0, 'Whittier'],
  ['Chapman', 'Chapman', 'SCIAC', 'CA', 3, 'h', 1, 'Orange'],
  ['Cal Lutheran', 'Cal Lutheran', 'SCIAC', 'CA', 2, 's', 1, 'Thousand Oaks'],
  ['La Verne', 'La Verne', 'SCIAC', 'CA', 2, 's', 0, 'La Verne'],
  ['Caltech', 'Caltech', 'SCIAC', 'CA', 1, 'm', 1, 'Pasadena'],
  // MIAC
  ['St. Olaf', 'St. Olaf', 'MIAC', 'MN', 2, 'h', 0, 'Northfield'],
  ['Carleton', 'Carleton', 'MIAC', 'MN', 1, 'm', 0, 'Northfield'],
  ['Macalester', 'Macalester', 'MIAC', 'MN', 1, 'm', 0, 'St. Paul'],
  ['Gustavus Adolphus', 'Gustavus', 'MIAC', 'MN', 2, 'h', 0, 'St. Peter'],
  ['St. John’s (MN)', "St. John's MN", 'MIAC', 'MN', 1, 's', 0, 'Collegeville'],
  ['Bethel (MN)', 'Bethel MN', 'MIAC', 'MN', 2, 's', 1, 'St. Paul'],
  ['Hamline', 'Hamline', 'MIAC', 'MN', 1, 's', 0, 'St. Paul'],
  ['Augsburg', 'Augsburg', 'MIAC', 'MN', 2, 's', 0, 'Minneapolis'],
  // ODAC
  ['Washington & Lee', 'W&L', 'ODAC', 'VA', 1, 'm', 1, 'Lexington'],
  ['Lynchburg', 'Lynchburg', 'ODAC', 'VA', 1, 's', 1, 'Lynchburg'],
  ['Roanoke', 'Roanoke', 'ODAC', 'VA', 1, 's', 0, 'Salem'],
  ['Randolph-Macon', 'Randolph-Macon', 'ODAC', 'VA', 1, 's', 0, 'Ashland'],
  ['Bridgewater (VA)', 'Bridgewater VA', 'ODAC', 'VA', 1, 's', 0, 'Bridgewater'],
  ['Guilford', 'Guilford', 'ODAC', 'NC', 1, 's', 0, 'Greensboro'],
  ['Virginia Wesleyan', 'Virginia Wesleyan', 'ODAC', 'VA', 1, 's', 0, 'Virginia Beach'],
  // Landmark
  ['Susquehanna', 'Susquehanna', 'Landmark', 'PA', 1, 's', 1, 'Selinsgrove'],
  ['Juniata', 'Juniata', 'Landmark', 'PA', 1, 's', 0, 'Huntingdon'],
  ['Elizabethtown', 'Elizabethtown', 'Landmark', 'PA', 1, 's', 1, 'Elizabethtown'],
  ['Catholic', 'Catholic', 'Landmark', 'DC', 2, 's', 1, 'Washington'],
  ['Moravian', 'Moravian', 'Landmark', 'PA', 1, 's', 1, 'Bethlehem'],
  ['Scranton', 'Scranton', 'Landmark', 'PA', 2, 's', 0, 'Scranton'],
  ['Goucher', 'Goucher', 'Landmark', 'MD', 1, 's', 0, 'Baltimore'],
  ['Drew', 'Drew', 'Landmark', 'NJ', 1, 's', 0, 'Madison'],
  // MAC (Middle Atlantic)
  ['Messiah', 'Messiah', 'MAC Commonwealth', 'PA', 2, 's', 1, 'Mechanicsburg'],
  ['Lycoming', 'Lycoming', 'MAC Commonwealth', 'PA', 1, 's', 0, 'Williamsport'],
  ['Stevens', 'Stevens', 'MAC Freedom', 'NJ', 2, 'h', 1, 'Hoboken'],
  ['DeSales', 'DeSales', 'MAC Freedom', 'PA', 1, 's', 0, 'Center Valley'],
  ['Misericordia', 'Misericordia', 'MAC Freedom', 'PA', 1, 's', 0, 'Dallas'],
  // Centennial-adjacent / NJAC
  ['Rowan', 'Rowan', 'NJAC', 'NJ', 4, 's', 1, 'Glassboro'],
  ['TCNJ', 'TCNJ', 'NJAC', 'NJ', 3, 'h', 1, 'Ewing'],
  ['Montclair State', 'Montclair St', 'NJAC', 'NJ', 4, 's', 0, 'Montclair'],
  ['Ramapo', 'Ramapo', 'NJAC', 'NJ', 3, 's', 0, 'Mahwah'],
  ['Kean', 'Kean', 'NJAC', 'NJ', 4, 'a', 0, 'Union'],
  ['Stockton', 'Stockton', 'NJAC', 'NJ', 3, 's', 0, 'Galloway'],
  ['William Paterson', 'William Paterson', 'NJAC', 'NJ', 3, 'a', 0, 'Wayne'],
  // Empire 8 / UNYAC / SUNYAC
  ['Nazareth', 'Nazareth', 'Empire 8', 'NY', 1, 's', 0, 'Rochester'],
  ['St. John Fisher', 'St. John Fisher', 'Empire 8', 'NY', 2, 's', 1, 'Rochester'],
  ['Utica', 'Utica', 'Empire 8', 'NY', 2, 's', 1, 'Utica'],
  ['Geneseo', 'Geneseo', 'SUNYAC', 'NY', 3, 'h', 0, 'Geneseo'],
  ['Cortland', 'Cortland', 'SUNYAC', 'NY', 3, 's', 0, 'Cortland'],
  ['Oneonta', 'Oneonta', 'SUNYAC', 'NY', 3, 's', 0, 'Oneonta'],
  ['Plattsburgh', 'Plattsburgh', 'SUNYAC', 'NY', 3, 's', 0, 'Plattsburgh'],
  ['Oswego', 'Oswego', 'SUNYAC', 'NY', 3, 's', 1, 'Oswego'],
  ['New Paltz', 'New Paltz', 'SUNYAC', 'NY', 3, 's', 0, 'New Paltz'],
  ['Brockport', 'Brockport', 'SUNYAC', 'NY', 3, 's', 0, 'Brockport'],
  // NECC / Little East / GNAC (D3)
  ['Keene State', 'Keene St', 'Little East', 'NH', 3, 's', 0, 'Keene'],
  ['Eastern Connecticut', 'Eastern Connecticut', 'Little East', 'CT', 3, 's', 0, 'Willimantic'],
  ['UMass Dartmouth', 'UMass Dartmouth', 'Little East', 'MA', 3, 's', 1, 'Dartmouth'],
  ['UMass Boston', 'UMass Boston', 'Little East', 'MA', 4, 's', 1, 'Boston'],
  ['Rhode Island College', 'Rhode Island College', 'Little East', 'RI', 3, 'a', 0, 'Providence'],
  ['Western New England', 'Western New England', 'CCC', 'MA', 2, 's', 1, 'Springfield'],
  ['Endicott', 'Endicott', 'CCC', 'MA', 2, 's', 1, 'Beverly'],
  ['Roger Williams', 'Roger Williams', 'CCC', 'RI', 2, 's', 1, 'Bristol'],
  ['Salve Regina', 'Salve Regina', 'CCC', 'RI', 1, 's', 0, 'Newport'],
  ['Gordon', 'Gordon', 'CCC', 'MA', 1, 's', 0, 'Wenham'],
  ['Wentworth', 'Wentworth', 'CCC', 'MA', 2, 's', 1, 'Boston'],
  // NCAC / OAC / Ohio
  ['Kenyon', 'Kenyon', 'NCAC', 'OH', 1, 'm', 0, 'Gambier'],
  ['Denison', 'Denison', 'NCAC', 'OH', 1, 'h', 0, 'Granville'],
  ['Wooster', 'Wooster', 'NCAC', 'OH', 1, 's', 0, 'Wooster'],
  ['Oberlin', 'Oberlin', 'NCAC', 'OH', 1, 'h', 0, 'Oberlin'],
  ['Wabash', 'Wabash', 'NCAC', 'IN', 1, 's', 0, 'Crawfordsville'],
  ['DePauw', 'DePauw', 'NCAC', 'IN', 1, 'h', 0, 'Greencastle'],
  ['Ohio Wesleyan', 'Ohio Wesleyan', 'NCAC', 'OH', 1, 's', 0, 'Delaware'],
  ['Wittenberg', 'Wittenberg', 'NCAC', 'OH', 1, 's', 0, 'Springfield'],
  ['John Carroll', 'John Carroll', 'OAC', 'OH', 2, 's', 1, 'University Heights'],
  ['Mount Union', 'Mount Union', 'OAC', 'OH', 2, 's', 1, 'Alliance'],
  ['Ohio Northern', 'Ohio Northern', 'OAC', 'OH', 1, 's', 1, 'Ada'],
  ['Otterbein', 'Otterbein', 'OAC', 'OH', 2, 's', 1, 'Westerville'],
  ['Baldwin Wallace', 'Baldwin Wallace', 'OAC', 'OH', 2, 's', 1, 'Berea'],
  // CCIW / Midwest
  ['Wheaton (IL)', 'Wheaton IL', 'CCIW', 'IL', 2, 'h', 1, 'Wheaton'],
  ['North Central (IL)', 'North Central IL', 'CCIW', 'IL', 2, 's', 1, 'Naperville'],
  ['Illinois Wesleyan', 'Illinois Wesleyan', 'CCIW', 'IL', 1, 'h', 0, 'Bloomington'],
  ['Carthage', 'Carthage', 'CCIW', 'WI', 2, 's', 1, 'Kenosha'],
  ['Elmhurst', 'Elmhurst', 'CCIW', 'IL', 1, 's', 1, 'Elmhurst'],
  ['Augustana (IL)', 'Augustana IL', 'CCIW', 'IL', 1, 's', 0, 'Rock Island'],
  ['Millikin', 'Millikin', 'CCIW', 'IL', 1, 's', 1, 'Decatur'],
  ['Grinnell', 'Grinnell', 'Midwest Conference', 'IA', 1, 'm', 0, 'Grinnell'],
  ['Lake Forest', 'Lake Forest', 'Midwest Conference', 'IL', 1, 'h', 0, 'Lake Forest'],
  ['Cornell College', 'Cornell College', 'Midwest Conference', 'IA', 1, 's', 0, 'Mount Vernon'],
  ['Beloit', 'Beloit', 'Midwest Conference', 'WI', 1, 's', 0, 'Beloit'],
  ['Ripon', 'Ripon', 'Midwest Conference', 'WI', 1, 's', 0, 'Ripon'],
  ['Luther', 'Luther', 'ARC', 'IA', 1, 's', 0, 'Decorah'],
  ['Loras', 'Loras', 'ARC', 'IA', 1, 's', 0, 'Dubuque'],
  ['Central (IA)', 'Central IA', 'ARC', 'IA', 1, 's', 0, 'Pella'],
  // WIAC
  ['UW-Whitewater', 'UW-Whitewater', 'WIAC', 'WI', 3, 's', 0, 'Whitewater'],
  ['UW-Oshkosh', 'UW-Oshkosh', 'WIAC', 'WI', 4, 's', 0, 'Oshkosh'],
  ['UW-Platteville', 'UW-Platteville', 'WIAC', 'WI', 2, 's', 1, 'Platteville'],
  ['UW-La Crosse', 'UW-La Crosse', 'WIAC', 'WI', 3, 's', 0, 'La Crosse'],
  ['UW-Stevens Point', 'UW-Stevens Point', 'WIAC', 'WI', 3, 's', 0, 'Stevens Point'],
  ['UW-Eau Claire', 'UW-Eau Claire', 'WIAC', 'WI', 3, 's', 0, 'Eau Claire'],
  // MIAA (Michigan) / HCAC / Heartland
  ['Calvin', 'Calvin', 'MIAA', 'MI', 2, 's', 1, 'Grand Rapids'],
  ['Hope', 'Hope', 'MIAA', 'MI', 2, 's', 1, 'Holland'],
  ['Kalamazoo', 'Kalamazoo', 'MIAA', 'MI', 1, 'h', 0, 'Kalamazoo'],
  ['Trine', 'Trine', 'MIAA', 'IN', 1, 's', 1, 'Angola'],
  ['Adrian', 'Adrian', 'MIAA', 'MI', 1, 's', 0, 'Adrian'],
  ['Rose-Hulman', 'Rose-Hulman', 'HCAC', 'IN', 1, 'h', 1, 'Terre Haute'],
  ['Transylvania', 'Transylvania', 'HCAC', 'KY', 1, 'h', 0, 'Lexington'],
  ['Franklin (IN)', 'Franklin IN', 'HCAC', 'IN', 1, 's', 0, 'Franklin'],
  // SAA / Southern D3
  ['Berry', 'Berry', 'SAA', 'GA', 2, 's', 1, 'Mount Berry'],
  ['Oglethorpe', 'Oglethorpe', 'SAA', 'GA', 1, 's', 0, 'Atlanta'],
  ['Rhodes', 'Rhodes', 'SAA', 'TN', 1, 'h', 0, 'Memphis'],
  ['Sewanee', 'Sewanee', 'SAA', 'TN', 1, 'h', 0, 'Sewanee'],
  ['Centre', 'Centre', 'SAA', 'KY', 1, 'h', 0, 'Danville'],
  ['Trinity (TX)', 'Trinity TX', 'SAA', 'TX', 1, 'h', 1, 'San Antonio'],
  ['Millsaps', 'Millsaps', 'SAA', 'MS', 1, 's', 0, 'Jackson'],
  ['Hendrix', 'Hendrix', 'SAA', 'AR', 1, 'h', 0, 'Conway'],
  // USA South / Southeast
  ['Christopher Newport', 'CNU', 'C2C', 'VA', 2, 's', 1, 'Newport News'],
  ['Mary Washington', 'Mary Washington', 'C2C', 'VA', 2, 's', 0, 'Fredericksburg'],
  ['Salisbury', 'Salisbury', 'C2C', 'MD', 3, 's', 0, 'Salisbury'],
  ['York (PA)', 'York PA', 'MAC', 'PA', 2, 's', 1, 'York'],
  // Florida / Deep South D3
  ['Eckerd', 'Eckerd', 'Sunshine State (D2)', 'FL', 1, 's', 0, 'St. Petersburg'],
  // Texas / Southwest D3
  ['UT Dallas', 'UT Dallas', 'ASC', 'TX', 4, 's', 1, 'Richardson'],
  ['Mary Hardin-Baylor', 'UMHB', 'ASC', 'TX', 2, 's', 0, 'Belton'],
  ['Texas Lutheran', 'Texas Lutheran', 'SCAC', 'TX', 1, 's', 0, 'Seguin'],
  ['Southwestern (TX)', 'Southwestern TX', 'SCAC', 'TX', 1, 'h', 0, 'Georgetown'],
  ['Colorado College', 'Colorado College', 'SCAC', 'CO', 1, 'm', 0, 'Colorado Springs'],
  ['Austin College', 'Austin College', 'SCAC', 'TX', 1, 's', 0, 'Sherman'],
  ['Schreiner', 'Schreiner', 'SCAC', 'TX', 1, 'a', 0, 'Kerrville'],
  // Northwest / West D3
  ['Puget Sound', 'Puget Sound', 'Northwest Conference', 'WA', 1, 'h', 0, 'Tacoma'],
  ['Whitworth', 'Whitworth', 'Northwest Conference', 'WA', 1, 's', 1, 'Spokane'],
  ['Whitman', 'Whitman', 'Northwest Conference', 'WA', 1, 'm', 0, 'Walla Walla'],
  ['Linfield', 'Linfield', 'Northwest Conference', 'OR', 1, 's', 0, 'McMinnville'],
  ['Pacific Lutheran', 'Pacific Lutheran', 'Northwest Conference', 'WA', 1, 's', 1, 'Tacoma'],
  ['Willamette', 'Willamette', 'Northwest Conference', 'OR', 1, 'h', 0, 'Salem'],
  ['George Fox', 'George Fox', 'Northwest Conference', 'OR', 2, 's', 1, 'Newberg'],
  ['Lewis & Clark', 'Lewis & Clark', 'Northwest Conference', 'OR', 1, 'h', 0, 'Portland'],
  // NYU-adjacent / Independents / UCAA
  ['Yeshiva', 'Yeshiva', 'Skyline', 'NY', 2, 's', 0, 'New York'],
  ['Farmingdale State', 'Farmingdale St', 'Skyline', 'NY', 3, 's', 1, 'Farmingdale'],
  ['Mount St. Vincent', 'Mount St. Vincent', 'Skyline', 'NY', 1, 'a', 0, 'Bronx'],
  ['Sarah Lawrence', 'Sarah Lawrence', 'Skyline', 'NY', 1, 'h', 0, 'Bronxville'],
  ['Purchase', 'Purchase', 'Skyline', 'NY', 2, 's', 0, 'Purchase'],
  ['SUNY Poly', 'SUNY Poly', 'Skyline', 'NY', 1, 's', 1, 'Utica'],
  ['Mount Saint Mary (NY)', 'Mount Saint Mary NY', 'Skyline', 'NY', 1, 'a', 0, 'Newburgh'],
  // PAC (Presidents' Athletic Conference)
  ['Grove City', 'Grove City', 'PAC', 'PA', 1, 'h', 1, 'Grove City'],
  ['Westminster (PA)', 'Westminster PA', 'PAC', 'PA', 1, 's', 0, 'New Wilmington'],
  ['Washington & Jefferson', 'W&J', 'PAC', 'PA', 1, 's', 0, 'Washington'],
  ['Bethany (WV)', 'Bethany WV', 'PAC', 'WV', 1, 'a', 0, 'Bethany'],
  ['Thiel', 'Thiel', 'PAC', 'PA', 1, 'a', 0, 'Greenville'],
  ['Geneva', 'Geneva', 'PAC', 'PA', 1, 's', 1, 'Beaver Falls'],
  ['Saint Vincent', 'Saint Vincent', 'PAC', 'PA', 1, 's', 0, 'Latrobe'],
  ['Chatham', 'Chatham', 'PAC', 'PA', 1, 's', 0, 'Pittsburgh'],
  ['Franciscan', 'Franciscan', 'PAC', 'OH', 1, 's', 1, 'Steubenville'],
  ['Waynesburg', 'Waynesburg', 'PAC', 'PA', 1, 's', 0, 'Waynesburg'],
  // MASCAC (Massachusetts state)
  ['Bridgewater State', 'Bridgewater St', 'MASCAC', 'MA', 3, 's', 0, 'Bridgewater'],
  ['Fitchburg State', 'Fitchburg St', 'MASCAC', 'MA', 2, 's', 0, 'Fitchburg'],
  ['Framingham State', 'Framingham St', 'MASCAC', 'MA', 2, 's', 0, 'Framingham'],
  ['Salem State', 'Salem St', 'MASCAC', 'MA', 3, 's', 0, 'Salem'],
  ['Westfield State', 'Westfield St', 'MASCAC', 'MA', 2, 's', 0, 'Westfield'],
  ['Worcester State', 'Worcester St', 'MASCAC', 'MA', 2, 's', 0, 'Worcester'],
  ['MCLA', 'MCLA', 'MASCAC', 'MA', 1, 's', 0, 'North Adams'],
  ['Mass Maritime', 'Mass Maritime', 'MASCAC', 'MA', 1, 's', 1, 'Buzzards Bay'],
  // GNAC (New England D3)
  ['Emmanuel (MA)', 'Emmanuel MA', 'GNAC', 'MA', 1, 's', 0, 'Boston'],
  ['Lasell', 'Lasell', 'GNAC', 'MA', 1, 'a', 0, 'Newton'],
  ['Regis (MA)', 'Regis MA', 'GNAC', 'MA', 1, 's', 0, 'Weston'],
  ['Albertus Magnus', 'Albertus Magnus', 'GNAC', 'CT', 1, 'a', 0, 'New Haven'],
  ['Norwich', 'Norwich', 'GNAC', 'VT', 1, 's', 1, 'Northfield'],
  ['Anna Maria', 'Anna Maria', 'GNAC', 'MA', 1, 'a', 0, 'Paxton'],
  ["Saint Joseph's (ME)", "Saint Joseph's ME", 'GNAC', 'ME', 1, 's', 0, 'Standish'],
  ['Colby-Sawyer', 'Colby-Sawyer', 'GNAC', 'NH', 1, 's', 0, 'New London'],
  ['Dean', 'Dean', 'GNAC', 'MA', 1, 'a', 0, 'Franklin'],
  // NAC (North Atlantic)
  ['Husson', 'Husson', 'NAC', 'ME', 1, 's', 0, 'Bangor'],
  ['Maine Maritime', 'Maine Maritime', 'NAC', 'ME', 1, 's', 1, 'Castine'],
  ['SUNY Cobleskill', 'SUNY Cobleskill', 'NAC', 'NY', 1, 'a', 0, 'Cobleskill'],
  ['SUNY Delhi', 'SUNY Delhi', 'NAC', 'NY', 1, 'a', 0, 'Delhi'],
  ['Northern Vermont', 'Northern Vermont', 'NAC', 'VT', 1, 'a', 0, 'Johnson'],
  // USA South
  ['Averett', 'Averett', 'USA South', 'VA', 1, 'a', 0, 'Danville'],
  ['Ferrum', 'Ferrum', 'USA South', 'VA', 1, 'a', 0, 'Ferrum'],
  ['Huntingdon', 'Huntingdon', 'USA South', 'AL', 1, 's', 0, 'Montgomery'],
  ['LaGrange', 'LaGrange', 'USA South', 'GA', 1, 's', 0, 'LaGrange'],
  ['Maryville (TN)', 'Maryville TN', 'USA South', 'TN', 1, 's', 0, 'Maryville'],
  ['Methodist', 'Methodist', 'USA South', 'NC', 1, 'a', 1, 'Fayetteville'],
  ['NC Wesleyan', 'NC Wesleyan', 'USA South', 'NC', 1, 'a', 0, 'Rocky Mount'],
  ['Piedmont', 'Piedmont', 'USA South', 'GA', 1, 's', 0, 'Demorest'],
  ['Covenant', 'Covenant', 'USA South', 'GA', 1, 'h', 0, 'Lookout Mountain'],
  ['Berea', 'Berea', 'USA South', 'KY', 1, 'h', 0, 'Berea'],
  ['William Peace', 'William Peace', 'USA South', 'NC', 1, 'a', 0, 'Raleigh'],
  // NACC (Northern Athletics)
  ['Aurora', 'Aurora', 'NACC', 'IL', 1, 's', 0, 'Aurora'],
  ['Concordia (WI)', 'Concordia WI', 'NACC', 'WI', 2, 's', 0, 'Mequon'],
  ['Concordia (IL)', 'Concordia IL', 'NACC', 'IL', 1, 's', 0, 'River Forest'],
  ['Marian (WI)', 'Marian WI', 'NACC', 'WI', 1, 'a', 0, 'Fond du Lac'],
  ['Rockford', 'Rockford', 'NACC', 'IL', 1, 'a', 0, 'Rockford'],
  ['Wisconsin Lutheran', 'Wisconsin Lutheran', 'NACC', 'WI', 1, 's', 0, 'Milwaukee'],
  ['Edgewood', 'Edgewood', 'NACC', 'WI', 1, 's', 0, 'Madison'],
  ['Lakeland', 'Lakeland', 'NACC', 'WI', 1, 'a', 0, 'Plymouth'],
  // UMAC / SLIAC (small Midwest)
  ['Bethany Lutheran', 'Bethany Lutheran', 'UMAC', 'MN', 1, 's', 0, 'Mankato'],
  ['Crown', 'Crown', 'UMAC', 'MN', 1, 'a', 0, 'St. Bonifacius'],
  ['Martin Luther', 'Martin Luther', 'UMAC', 'MN', 1, 'a', 0, 'New Ulm'],
  ['Northwestern (MN)', 'Northwestern MN', 'UMAC', 'MN', 1, 's', 0, 'St. Paul'],
  ['Fontbonne', 'Fontbonne', 'SLIAC', 'MO', 1, 'a', 0, 'St. Louis'],
  ['Webster', 'Webster', 'SLIAC', 'MO', 1, 's', 0, 'St. Louis'],
  ['Greenville', 'Greenville', 'SLIAC', 'IL', 1, 'a', 0, 'Greenville'],
  ['Principia', 'Principia', 'SLIAC', 'IL', 1, 's', 0, 'Elsah'],
  ['Blackburn', 'Blackburn', 'SLIAC', 'IL', 1, 'a', 0, 'Carlinville'],
  // CUNYAC
  ['Baruch', 'Baruch', 'CUNYAC', 'NY', 4, 's', 0, 'New York'],
  ['Brooklyn College', 'Brooklyn College', 'CUNYAC', 'NY', 3, 's', 0, 'Brooklyn'],
  ['Hunter', 'Hunter', 'CUNYAC', 'NY', 4, 's', 0, 'New York'],
  ['City College of New York', 'CCNY', 'CUNYAC', 'NY', 3, 's', 1, 'New York'],
  ['Lehman', 'Lehman', 'CUNYAC', 'NY', 3, 'a', 0, 'Bronx'],
  ['Staten Island', 'CSI', 'CUNYAC', 'NY', 3, 's', 1, 'Staten Island'],
  ['York (NY)', 'York NY', 'CUNYAC', 'NY', 2, 'a', 0, 'Jamaica'],
  // Empire 8 / additional NY & PA D3
  ['Alfred', 'Alfred', 'Empire 8', 'NY', 1, 's', 1, 'Alfred'],
  ['Elmira', 'Elmira', 'Empire 8', 'NY', 1, 's', 0, 'Elmira'],
  ['Hartwick', 'Hartwick', 'Empire 8', 'NY', 1, 's', 0, 'Oneonta'],
  ['Houghton', 'Houghton', 'Empire 8', 'NY', 1, 's', 0, 'Houghton'],
  ['Sage', 'Russell Sage', 'Empire 8', 'NY', 1, 'a', 0, 'Troy'],
  // Additional Northeast / Mid-Atlantic academic D3
  ['Wells', 'Wells', 'Independent', 'NY', 1, 's', 0, 'Aurora'],
  ['Marymount (VA)', 'Marymount VA', 'Atlantic East', 'VA', 1, 'a', 0, 'Arlington'],
  ['Marywood', 'Marywood', 'Atlantic East', 'PA', 1, 's', 0, 'Scranton'],
  ['Neumann', 'Neumann', 'Atlantic East', 'PA', 1, 'a', 0, 'Aston'],
  ['Gwynedd Mercy', 'Gwynedd Mercy', 'Atlantic East', 'PA', 1, 'a', 0, 'Gwynedd Valley'],
  ['Immaculata', 'Immaculata', 'Atlantic East', 'PA', 1, 'a', 0, 'Immaculata'],
  ['Centenary (NJ)', 'Centenary NJ', 'Atlantic East', 'NJ', 1, 'a', 0, 'Hackettstown'],
  ['Arcadia', 'Arcadia', 'MAC Commonwealth', 'PA', 1, 's', 0, 'Glenside'],
  ['Albright', 'Albright', 'MAC Commonwealth', 'PA', 1, 's', 0, 'Reading'],
  ['Alvernia', 'Alvernia', 'MAC Commonwealth', 'PA', 1, 'a', 0, 'Reading'],
  ['Hood', 'Hood', 'MAC Commonwealth', 'MD', 1, 's', 0, 'Frederick'],
  ['Widener', 'Widener', 'MAC Commonwealth', 'PA', 2, 's', 1, 'Chester'],
  ['Eastern (PA)', 'Eastern PA', 'MAC Commonwealth', 'PA', 1, 's', 0, 'St. Davids'],
  ['Lebanon Valley', 'Lebanon Valley', 'MAC Commonwealth', 'PA', 1, 's', 1, 'Annville'],
  ['Stevenson', 'Stevenson', 'MAC Commonwealth', 'MD', 2, 's', 0, 'Owings Mills'],
  ['King’s (PA)', "King's PA", 'MAC Freedom', 'PA', 1, 's', 0, 'Wilkes-Barre'],
  ['Wilkes', 'Wilkes', 'MAC Freedom', 'PA', 1, 's', 1, 'Wilkes-Barre'],
  ['FDU-Florham', 'FDU-Florham', 'MAC Freedom', 'NJ', 1, 's', 0, 'Madison'],
  // More SUNYAC
  ['Buffalo State', 'Buffalo St', 'SUNYAC', 'NY', 3, 'a', 0, 'Buffalo'],
  ['Fredonia', 'Fredonia', 'SUNYAC', 'NY', 2, 's', 0, 'Fredonia'],
  ['Potsdam', 'Potsdam', 'SUNYAC', 'NY', 2, 's', 0, 'Potsdam'],
  ['Morrisville', 'Morrisville', 'SUNYAC', 'NY', 1, 'a', 1, 'Morrisville'],
  // NEAC
  ['Penn State Berks', 'PSU Berks', 'NEAC', 'PA', 1, 's', 1, 'Reading'],
  ['Penn State Harrisburg', 'PSU Harrisburg', 'NEAC', 'PA', 2, 's', 1, 'Middletown'],
  ['Keystone', 'Keystone', 'NEAC', 'PA', 1, 'a', 0, 'La Plume'],
  ['Cairn', 'Cairn', 'NEAC', 'PA', 1, 'a', 0, 'Langhorne'],
  ['Gallaudet', 'Gallaudet', 'NEAC', 'DC', 1, 's', 0, 'Washington'],
  ['SUNY Canton', 'SUNY Canton', 'NEAC', 'NY', 1, 'a', 1, 'Canton'],
  ['Lancaster Bible', 'Lancaster Bible', 'NEAC', 'PA', 1, 'a', 0, 'Lancaster'],
  // More Texas / SCAC / ASC D3
  ['Concordia (TX)', 'Concordia TX', 'ASC', 'TX', 2, 's', 0, 'Austin'],
  ['Hardin-Simmons', 'Hardin-Simmons', 'ASC', 'TX', 1, 's', 1, 'Abilene'],
  ['Sul Ross State', 'Sul Ross St', 'ASC', 'TX', 1, 'a', 0, 'Alpine'],
  ['McMurry', 'McMurry', 'ASC', 'TX', 1, 'a', 0, 'Abilene'],
  ['Howard Payne', 'Howard Payne', 'ASC', 'TX', 1, 'a', 0, 'Brownwood'],
  ['LeTourneau', 'LeTourneau', 'ASC', 'TX', 1, 's', 1, 'Longview'],
  ['East Texas Baptist', 'East Texas Baptist', 'ASC', 'TX', 1, 'a', 0, 'Marshall'],
  ['Belhaven', 'Belhaven', 'Collegiate Conf. South', 'MS', 1, 'a', 0, 'Jackson'],
  // Great South / Collegiate Conference of the South
  ['Fisk', 'Fisk', 'Collegiate Conf. South', 'TN', 1, 's', 0, 'Nashville'],
  // More Michigan / Midwest D3
  ['Albion', 'Albion', 'MIAA', 'MI', 1, 's', 0, 'Albion'],
  ['Alma', 'Alma', 'MIAA', 'MI', 1, 's', 0, 'Alma'],
  ['Olivet (MI)', 'Olivet MI', 'MIAA', 'MI', 1, 'a', 0, 'Olivet'],
  ['Manchester', 'Manchester', 'HCAC', 'IN', 1, 's', 0, 'North Manchester'],
  ['Anderson (IN)', 'Anderson IN', 'HCAC', 'IN', 1, 's', 0, 'Anderson'],
  ['Bluffton', 'Bluffton', 'HCAC', 'OH', 1, 's', 0, 'Bluffton'],
  ['Mount St. Joseph', 'Mount St. Joseph', 'HCAC', 'OH', 1, 's', 0, 'Cincinnati'],
  ['Hanover', 'Hanover', 'HCAC', 'IN', 1, 's', 0, 'Hanover'],
  ['Earlham', 'Earlham', 'HCAC', 'IN', 1, 'h', 0, 'Richmond'],
  ['Defiance', 'Defiance', 'HCAC', 'OH', 1, 'a', 0, 'Defiance'],
  // More CCIW / Iowa / Midwest
  ['North Park', 'North Park', 'CCIW', 'IL', 1, 's', 0, 'Chicago'],
  ['Wartburg', 'Wartburg', 'ARC', 'IA', 1, 's', 1, 'Waverly'],
  ['Coe', 'Coe', 'ARC', 'IA', 1, 'h', 0, 'Cedar Rapids'],
  ['Buena Vista', 'Buena Vista', 'ARC', 'IA', 1, 's', 0, 'Storm Lake'],
  ['Simpson (IA)', 'Simpson IA', 'ARC', 'IA', 1, 's', 0, 'Indianola'],
  ['Dubuque', 'Dubuque', 'ARC', 'IA', 1, 'a', 1, 'Dubuque'],
  ['Nebraska Wesleyan', 'Nebraska Wesleyan', 'ARC', 'NE', 1, 's', 0, 'Lincoln'],
  ['Illinois College', 'Illinois College', 'Midwest Conference', 'IL', 1, 's', 0, 'Jacksonville'],
  ['Knox', 'Knox', 'Midwest Conference', 'IL', 1, 'h', 0, 'Galesburg'],
  ['Monmouth (IL)', 'Monmouth IL', 'Midwest Conference', 'IL', 1, 's', 0, 'Monmouth'],
  ['Lawrence', 'Lawrence', 'Midwest Conference', 'WI', 1, 'h', 0, 'Appleton'],
  ['St. Norbert', 'St. Norbert', 'Midwest Conference', 'WI', 1, 's', 0, 'De Pere'],
  // More Southeast / Virginia / ODAC
  ['Shenandoah', 'Shenandoah', 'ODAC', 'VA', 2, 's', 0, 'Winchester'],
  ['Eastern Mennonite', 'Eastern Mennonite', 'ODAC', 'VA', 1, 's', 0, 'Harrisonburg'],
  ['Hampden-Sydney', 'Hampden-Sydney', 'ODAC', 'VA', 1, 'h', 0, 'Hampden-Sydney'],
  // More SoCal / West D3
  ['UC Santa Cruz', 'UC Santa Cruz', 'C2C', 'CA', 4, 'h', 1, 'Santa Cruz'],
]

// ─── NAIA ──────────────────────────────────────────────────────────────────
const NAIA: Row[] = [
  ['Lindsey Wilson', 'Lindsey Wilson', 'Mid-South', 'KY', 2, 'a', 0, 'Columbia'],
  ['Cumberlands', 'Cumberlands', 'Mid-South', 'KY', 2, 'a', 0, 'Williamsburg'],
  ['Georgetown (KY)', 'Georgetown KY', 'Mid-South', 'KY', 1, 's', 0, 'Georgetown'],
  ['Campbellsville', 'Campbellsville', 'Mid-South', 'KY', 2, 'a', 0, 'Campbellsville'],
  ['Cornerstone', 'Cornerstone', 'Crossroads', 'MI', 1, 's', 0, 'Grand Rapids'],
  ['Indiana Wesleyan', 'Indiana Wesleyan', 'Crossroads', 'IN', 2, 's', 0, 'Marion'],
  ['Marian (IN)', 'Marian IN', 'Crossroads', 'IN', 1, 's', 1, 'Indianapolis'],
  ['Bethel (IN)', 'Bethel IN', 'Crossroads', 'IN', 1, 's', 0, 'Mishawaka'],
  ['Grace', 'Grace', 'Crossroads', 'IN', 1, 's', 0, 'Winona Lake'],
  ['Rio Grande', 'Rio Grande', 'River States', 'OH', 1, 'a', 0, 'Rio Grande'],
  ['Embry-Riddle (Prescott)', 'ERAU Prescott', 'Cal Pac', 'AZ', 2, 's', 1, 'Prescott'],
  ['Ottawa (AZ)', 'Ottawa AZ', 'Golden State', 'AZ', 2, 'a', 0, 'Surprise'],
  ['Vanguard', 'Vanguard', 'Golden State', 'CA', 1, 's', 0, 'Costa Mesa'],
  ['Westmont', 'Westmont', 'Golden State', 'CA', 1, 'h', 0, 'Santa Barbara'],
  ['The Master’s', "The Master's", 'Golden State', 'CA', 1, 's', 0, 'Santa Clarita'],
  ['William Carey', 'William Carey', 'Southern States', 'MS', 2, 'a', 0, 'Hattiesburg'],
  ['Mobile', 'Mobile', 'Southern States', 'AL', 1, 's', 0, 'Mobile'],
  ['Keiser', 'Keiser', 'Sun', 'FL', 2, 's', 0, 'West Palm Beach'],
  ['Thomas (GA)', 'Thomas GA', 'Sun', 'GA', 1, 'a', 0, 'Thomasville'],
  ['Southeastern (FL)', 'Southeastern FL', 'Sun', 'FL', 2, 'a', 0, 'Lakeland'],
  ['Oklahoma Wesleyan', 'Oklahoma Wesleyan', 'Sooner', 'OK', 1, 'a', 0, 'Bartlesville'],
  ['Science & Arts of Oklahoma', 'USAO', 'Sooner', 'OK', 1, 'a', 0, 'Chickasha'],
  ['MidAmerica Nazarene', 'MidAmerica Nazarene', 'Heart', 'KS', 1, 'a', 0, 'Olathe'],
  ['Benedictine (KS)', 'Benedictine KS', 'Heart', 'KS', 1, 's', 1, 'Atchison'],
  ['Park', 'Park', 'Heart', 'MO', 2, 'a', 0, 'Parkville'],
  ['Northwestern (IA)', 'Northwestern IA', 'GPAC', 'IA', 1, 's', 0, 'Orange City'],
  ['Hastings', 'Hastings', 'GPAC', 'NE', 1, 's', 0, 'Hastings'],
  ['Concordia (NE)', 'Concordia NE', 'GPAC', 'NE', 1, 's', 0, 'Seward'],
  ['Rocky Mountain', 'Rocky Mountain', 'Frontier', 'MT', 1, 's', 1, 'Billings'],
  ['Providence (MT)', 'Providence MT', 'Frontier', 'MT', 1, 'a', 0, 'Great Falls'],
  ['Southern Oregon', 'Southern Oregon', 'Cascade', 'OR', 2, 's', 0, 'Ashland'],
  ['Corban', 'Corban', 'Cascade', 'OR', 1, 's', 0, 'Salem'],
  ['Northwest (WA)', 'Northwest WA', 'Cascade', 'WA', 1, 'a', 0, 'Kirkland'],
  ['Eastern Oregon', 'Eastern Oregon', 'Cascade', 'OR', 1, 'a', 0, 'La Grande'],
  ['College of Idaho', 'College of Idaho', 'Cascade', 'ID', 1, 's', 0, 'Caldwell'],
  ['Lewis-Clark State', 'Lewis-Clark St', 'Cascade', 'ID', 1, 'a', 0, 'Lewiston'],
  // Continental / Kansas / Sooner
  ['Kansas Wesleyan', 'Kansas Wesleyan', 'KCAC', 'KS', 1, 'a', 0, 'Salina'],
  ['Bethany (KS)', 'Bethany KS', 'KCAC', 'KS', 1, 'a', 0, 'Lindsborg'],
  ['Friends', 'Friends', 'KCAC', 'KS', 1, 'a', 0, 'Wichita'],
  ['Sterling', 'Sterling', 'KCAC', 'KS', 1, 'a', 0, 'Sterling'],
  ['Southwestern (KS)', 'Southwestern KS', 'KCAC', 'KS', 1, 'a', 0, 'Winfield'],
  ['Oklahoma City', 'Oklahoma City', 'Sooner', 'OK', 1, 's', 0, 'Oklahoma City'],
  ['SW Assemblies of God', 'SAGU', 'Sooner', 'TX', 1, 'a', 0, 'Waxahachie'],
  ['Wayland Baptist', 'Wayland Baptist', 'Sooner', 'TX', 1, 'a', 0, 'Plainview'],
  ['John Brown', 'John Brown', 'Sooner', 'AR', 1, 's', 0, 'Siloam Springs'],
  // Appalachian / Mid-South / River States more
  ['Milligan', 'Milligan', 'Appalachian', 'TN', 1, 's', 0, 'Milligan'],
  ['Bryan', 'Bryan', 'Appalachian', 'TN', 1, 's', 0, 'Dayton'],
  ['Reinhardt', 'Reinhardt', 'Appalachian', 'GA', 1, 'a', 0, 'Waleska'],
  ['Truett McConnell', 'Truett McConnell', 'Appalachian', 'GA', 1, 'a', 0, 'Cleveland'],
  ['Point (GA)', 'Point GA', 'Appalachian', 'GA', 1, 'a', 0, 'West Point'],
  ['Union (KY)', 'Union KY', 'Mid-South', 'KY', 1, 'a', 0, 'Barbourville'],
  ['Pikeville', 'Pikeville', 'Mid-South', 'KY', 1, 'a', 0, 'Pikeville'],
  ['Life', 'Life', 'Mid-South', 'GA', 1, 'a', 0, 'Marietta'],
  ['Shawnee State', 'Shawnee St', 'River States', 'OH', 2, 'a', 0, 'Portsmouth'],
  ['West Virginia Tech', 'WV Tech', 'River States', 'WV', 1, 'a', 1, 'Beckley'],
  ['Midway', 'Midway', 'River States', 'KY', 1, 'a', 0, 'Midway'],
  ['Brescia', 'Brescia', 'River States', 'KY', 1, 'a', 0, 'Owensboro'],
  // Great Plains / North Star
  ['Dordt', 'Dordt', 'GPAC', 'IA', 1, 's', 1, 'Sioux Center'],
  ['Morningside', 'Morningside', 'GPAC', 'IA', 1, 's', 0, 'Sioux City'],
  ['Dakota Wesleyan', 'Dakota Wesleyan', 'GPAC', 'SD', 1, 'a', 0, 'Mitchell'],
  ['Jamestown', 'Jamestown', 'GPAC', 'ND', 1, 'a', 0, 'Jamestown'],
  ['Waldorf', 'Waldorf', 'North Star', 'IA', 1, 'a', 0, 'Forest City'],
  ['Valley City State', 'Valley City St', 'North Star', 'ND', 1, 'a', 0, 'Valley City'],
  ['Mayville State', 'Mayville St', 'North Star', 'ND', 1, 'a', 0, 'Mayville'],
]

// ─── JUCO ──────────────────────────────────────────────────────────────────
const JUCO: Row[] = [
  ['Iowa Western CC', 'Iowa Western', 'NJCAA D1', 'IA', 2, 'a', 1, 'Council Bluffs'],
  ['Tyler Junior College', 'Tyler JC', 'NJCAA D1', 'TX', 3, 'a', 0, 'Tyler'],
  ['Eastern Florida State', 'Eastern Florida St', 'NJCAA D1', 'FL', 3, 'a', 0, 'Melbourne'],
  ['Monroe College', 'Monroe', 'NJCAA D1', 'NY', 2, 'a', 0, 'Bronx'],
  ['Hillsborough CC', 'Hillsborough CC', 'NJCAA D1', 'FL', 4, 'a', 0, 'Tampa'],
  ['Pima CC', 'Pima CC', 'NJCAA D1', 'AZ', 4, 'a', 0, 'Tucson'],
  ['Yavapai College', 'Yavapai', 'NJCAA D1', 'AZ', 2, 'a', 0, 'Prescott'],
  ['Paradise Valley CC', 'Paradise Valley CC', 'NJCAA D1', 'AZ', 3, 'a', 0, 'Phoenix'],
  ['Cowley College', 'Cowley', 'NJCAA D1', 'KS', 2, 'a', 0, 'Arkansas City'],
  ['Barton CC', 'Barton CC', 'NJCAA D1', 'KS', 2, 'a', 0, 'Great Bend'],
  ['Indian Hills CC', 'Indian Hills CC', 'NJCAA D1', 'IA', 2, 'a', 0, 'Ottumwa'],
  ['Southwestern (IA)', 'Southwestern CC IA', 'NJCAA D1', 'IA', 1, 'a', 0, 'Creston'],
  ['Schoolcraft College', 'Schoolcraft', 'NJCAA D1', 'MI', 3, 'a', 0, 'Livonia'],
  ['Rowan College', 'Rowan College', 'NJCAA D1', 'NJ', 2, 'a', 0, 'Sewell'],
  ['Mercer County CC', 'Mercer County CC', 'NJCAA D1', 'NJ', 2, 'a', 0, 'West Windsor'],
  ['Northampton CC', 'Northampton CC', 'NJCAA D2', 'PA', 3, 'a', 0, 'Bethlehem'],
  ['Community College of Baltimore', 'CCBC', 'NJCAA D2', 'MD', 3, 'a', 0, 'Baltimore'],
  ['County College of Morris', 'CCM', 'NJCAA D2', 'NJ', 2, 'a', 0, 'Randolph'],
  ['Richland College', 'Richland', 'NJCAA D3', 'TX', 4, 'a', 0, 'Dallas'],
  ['Santa Rosa JC', 'Santa Rosa JC', 'CCCAA', 'CA', 4, 'a', 0, 'Santa Rosa'],
  ['Irvine Valley College', 'Irvine Valley', 'CCCAA', 'CA', 3, 'a', 0, 'Irvine'],
  ['Mt. San Antonio College', 'Mt. SAC', 'CCCAA', 'CA', 4, 'a', 0, 'Walnut'],
  ['Fresno City College', 'Fresno City', 'CCCAA', 'CA', 4, 'a', 0, 'Fresno'],
  ['Cypress College', 'Cypress', 'CCCAA', 'CA', 4, 'a', 0, 'Cypress'],
  ['Orange Coast College', 'Orange Coast', 'CCCAA', 'CA', 4, 'a', 0, 'Costa Mesa'],
  ['Chabot College', 'Chabot', 'CCCAA', 'CA', 4, 'a', 0, 'Hayward'],
  ['MiraCosta College', 'MiraCosta', 'CCCAA', 'CA', 3, 'a', 0, 'Oceanside'],
  ['Butler CC', 'Butler CC', 'NJCAA D1', 'KS', 2, 'a', 0, 'El Dorado'],
  ['Hutchinson CC', 'Hutchinson CC', 'NJCAA D1', 'KS', 2, 'a', 0, 'Hutchinson'],
  ['Johnson County CC', 'Johnson County CC', 'NJCAA D1', 'KS', 4, 'a', 0, 'Overland Park'],
  ['Southwestern Illinois', 'SWIC', 'NJCAA D1', 'IL', 3, 'a', 0, 'Belleville'],
  ['Parkland College', 'Parkland', 'NJCAA D1', 'IL', 3, 'a', 0, 'Champaign'],
  ['Lansing CC', 'Lansing CC', 'NJCAA D1', 'MI', 3, 'a', 0, 'Lansing'],
  ['Genesee CC', 'Genesee CC', 'NJCAA D3', 'NY', 1, 'a', 0, 'Batavia'],
  ['Ocean County College', 'Ocean County', 'NJCAA D3', 'NJ', 2, 'a', 0, 'Toms River'],
  ['Brookdale CC', 'Brookdale CC', 'NJCAA D3', 'NJ', 3, 'a', 0, 'Lincroft'],
  ['Harford CC', 'Harford CC', 'NJCAA D2', 'MD', 2, 'a', 0, 'Bel Air'],
  ['Montgomery College', 'Montgomery College', 'NJCAA D3', 'MD', 4, 'a', 0, 'Rockville'],
  ['NOVA', 'Northern Virginia CC', 'NJCAA D3', 'VA', 4, 'a', 0, 'Annandale'],
]

// ─── Build + insert ─────────────────────────────────────────────────────────
function build(rows: Row[], division: string) {
  return rows
    .filter(r => STATE_REGION[r[3]]) // guard: only mapped states
    .map(r => {
      const [name, short, conference, state, enr, aca, eng, city] = r
      const region = STATE_REGION[state]
      if (!region) throw new Error(`No region for state "${state}" (${name})`)
      return {
        name, short_name: short, division, conference, state, region,
        enrollment_band: ENR[enr], academic_band: ACA[aca],
        has_engineering: eng === 1, city, note: null as string | null,
      }
    })
}

async function main() {
  const all = [
    ...build(D1, 'D1'), ...build(D2, 'D2'), ...build(D3, 'D3'),
    ...build(NAIA, 'NAIA'), ...build(JUCO, 'JUCO'),
  ]
  // De-dup by (name, state) — a few schools appear across divisions historically; keep first.
  const seen = new Set<string>()
  const rows = all.filter(r => {
    const k = `${r.name}|${r.state}`
    if (seen.has(k)) return false
    seen.add(k)
    return true
  })

  console.log(`Prepared ${rows.length} rows (D1/D2/D3/NAIA/JUCO).`)

  // Idempotent: clear then insert in chunks.
  const { error: delErr } = await sb.from('discovery_schools').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  if (delErr) { console.error('Delete failed:', delErr.message); process.exit(1) }

  for (let i = 0; i < rows.length; i += 200) {
    const chunk = rows.slice(i, i + 200)
    const { error } = await sb.from('discovery_schools').insert(chunk)
    if (error) { console.error(`Insert chunk ${i} failed:`, error.message); process.exit(1) }
  }

  const { count } = await sb.from('discovery_schools').select('*', { count: 'exact', head: true })
  console.log(`✅ Seeded ${count} discovery_schools.`)

  // Facet distribution summary
  const byDiv: Record<string, number> = {}, byRegion: Record<string, number> = {}
  for (const r of rows) { byDiv[r.division] = (byDiv[r.division] ?? 0) + 1; byRegion[r.region] = (byRegion[r.region] ?? 0) + 1 }
  console.log('By division:', JSON.stringify(byDiv))
  console.log('By region:  ', JSON.stringify(byRegion))
}

main()
