-- ============================================================
-- Seed: 63 schools — run AFTER 001_initial_schema.sql
-- Paste and run each numbered block separately if needed.
-- ============================================================

-- Block 1: Tier A schools (8 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('University of Rochester','Rochester','A','D3','UAA','Rochester, NY','Ongoing Conversation','2026-04-03','Ben Cross – Head Coach','bc006j@sports.rochester.edu','Target','Completed',true,E'Got a personalized email back from Coach Cross.\n\nThanks for reaching out about your interest. I am impressed with your film as you show great technical skill to take on defenders and provide amazing services from the wide areas. I also like how seriously you take your academics and are interested in','',null,null),
('CO School of Mines','Mines','A','D2','RMAC','Golden, CO','Ongoing Conversation','2025-11-27','Ben Fredrickson – Interim/Assistant Coach','ben.fredrickson@mines.edu','Target','Completed',true,E'Signed up for Feb 7, 2026 ID Camp\nPlayed meh and got rejection email\nDid ID CAMP #1 - June 7-8, 2025\nEmailed on 3/15 with update\nEmailed about PHX on 2/12 (responded)','Follow up with MLS NEXT Fest Update',null,null),
('Milwaukee School of Engineering (MSOE)','MSOE','A','D3','Northern Athletics Collegiate Conference (NACC)','Milwaukee, WI','Ongoing Conversation','2025-12-03','Rob Harrington - Head Men''s Soccer Coach','harrington@msoe.edu','Likely','To Do',true,'What do you want to study?','Follow up with MLS NEXT Fest Update',null,null),
('WPI','WPI','A','D3','NEWMAC','Worcester, MA','Intro Sent','2025-11-28','Brian Kelley – Head Coach','bkelley@wpi.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Case Western','Case Western','A','D3','UAA','Cleveland, OH','Ongoing Conversation','2025-12-03','Carter Poe – Head Coach','ccp51@case.edu','Reach','Completed',true,E'In AZ\nComplete Schedule Form\nFilled out schedule form for MLS NEXT Fest','Follow up with MLS NEXT Fest Update',null,null),
('Lafayette College','Lafayette','A','D1','Patriot League','Easton, PA','Ongoing Conversation','2025-12-03','Dennis Bohn - Head Coach','bohnd@lafayette.edu','Reach','Completed',true,E'ID Camp in FL\nIn Arizona','Follow up with MLS NEXT Fest Update',null,null),
('RPI','RPI','A','D3','Liberty League','Troy, NY','Intro Sent','2025-12-03','Adam Clinton – Head Coach','clinta@rpi.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Cal Poly San Luis Obispo (Cal Poly SLO)','Cal Poly SLO','A','D1','Big West','San Luis Obispo, CA','Intro Sent','2025-12-03','Oige Kennedy – Head Coach','okennedy@calpoly.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null);

-- Block 2: Tier B schools — part 1 (8 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Northeastern','Northeastern','B','D1','CAA','Boston, MA','Intro Sent','2025-12-03','Jeremy Bonomo – Head Coach','j.bonomo@northeastern.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('South Dakota Mines (South Dakota School of Mines & Technology)','SD Mines','B','D2','Rocky Mountain Athletic Conference (RMAC)','Rapid City, SD','Intro Sent','2025-11-28','Teren Schuster - Head Coach','Teren.Schuster@sdsmt.edu','Likely',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Cal Poly Pomona','Cal Poly Pomona','B','D2','CCAA (D2)','Pomona, CA','Intro Sent','2025-11-28','Matt O''Sullivan – Head Coach','mosulliv@cpp.edu','Likely',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('VA Tech','VA Tech','B','D1','ACC','Blacksburg, VA','Intro Sent','2025-12-03','Mike Brizendine – Head Coach','vtmsoccer@vt.edu','Target','Completed (no email yet)',true,'','Follow up with MLS NEXT Fest Update',null,null),
('Illinois Institute of Technology (Illinois Tech)','Illinois Tech','B','D3','Northern Athletics Collegiate Conference (NACC)','Chicago, IL (Bronzeville, near downtown)','Intro Sent','2025-11-28','Marlon McKenzie - Head Men''s Soccer Coach','mmckenzie1@illinoistech.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Rochester Institute of Technology (RIT)','RIT','B','D3','Liberty League','Rochester, NY (Henrietta suburb)','Intro Sent','2025-12-03','Bill Garno - Head Coach','bill.garno@rit.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Lehigh University','Lehigh','B','D1','Patriot League','Bethlehem, PA','Ongoing Conversation','2025-12-03','Dean Koski – Head Coach; Ryan Hess – Associate Head Coach; Matt Giacalone – Assistant Coach','dk0a@lehigh.edu','Reach','Completed',true,'Yes in Arizona',E'Follow up with MLS NEXT Fest Update\nRQ',null,null),
('Bucknell University','Bucknell','B','D1','Patriot League','Lewisburg, PA','Ongoing Conversation','2025-12-03','Dave Brandt – Head Coach; David Yates – Assistant Coach; Casey Penrod – Assistant Coach','db055@bucknell.edu','Reach','Completed',true,E'Yes in Phoenix\nHigh Press\nStrong Mental Game','Follow up with MLS NEXT Fest Update',null,null);

-- Block 3: Tier B schools — part 2 (7 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Stevens Institute of Technology','Stevens','B','D3','MAC Freedom (Middle Atlantic Conference)','Hoboken, NJ','Intro Sent','2025-12-03','Dale Jordan - Head Coach','djordan@stevens.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Carnegie Mellon','CMU','B','D3','UAA','Pittsburgh, PA','Ongoing Conversation','2025-12-03','Brandon Bowman – Head Coach','bhbowman@andrew.cmu.edu','Far Reach','Completed',true,E'Played ok but not great. Got middling respone from Coach Macklin\nAttended ID Camp in September 2025','Follow up with MLS NEXT Fest Update',null,null),
('Washington University','WashU','B','D3','UAA','St. Louis, MO','Intro Sent','2025-12-03','Andrew Bordelon – Head Coach','bordelon@wustl.edu','Far Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Cornell','Cornell','B','D1','Ivy League','Ithaca, NY','Intro Sent','2025-11-27','John Smith – Head Coach (Dr. Daniel P. Wood Endowed Chair)','msoccer@cornell.edu','Far Reach','Updated (no email yet)',true,'','Follow up with MLS NEXT Fest Update',null,null),
('Middlebury','Middlebury','B','D3','NESCAC','Middlebury, VT','Ongoing Conversation','2025-12-03','Alex Elias – Head Men''s Soccer Coach','aelias@middlebury.edu','Far Reach','Completed',true,E'Personal Intro\nID Camp Info',E'Follow up with MLS NEXT Fest Update\nLet them know which halves you''re starting.',null,null),
('Duke','Duke','B','D1','ACC','Durham, NC','Intro Sent','2025-12-03','John Kerr – Head Coach','jjk21@duke.edu','Far Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('NC State','NC State','C','D1','ACC','Raleigh, NC','Intro Sent','2025-12-03','Marc Hubbard – Head Coach','mens_soccer@ncsu.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null);

-- Block 4: Tier C schools — part 1 (9 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Penn State','Penn State','C','D1','Big Ten','University Park, PA','Intro Sent','2025-12-03','Rob Dow – Head Coach','msoccer@psu.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('UVA','UVA','C','D1','ACC','Charlottesville, VA','Ongoing Conversation','2025-11-28','George Gelnovatch – Head Coach','gg4n@virginia.edu','Reach','Completed (no email yet)',true,E'ID camp\nYes in Arizona','Follow up with MLS NEXT Fest Update',null,null),
('U of Washington','UW','C','D1','Pac-12 (men''s soccer)','Seattle, WA','Ongoing Conversation','2025-11-30','Jamie Clark – Head Coach','huskysoccer@uw.edu','Reach','Completed (no email yet)',true,'Yes in Arizona','Follow up with MLS NEXT Fest Update',null,null),
('U Michigan','Michigan','C','D1','Big Ten','Ann Arbor, MI','Intro Sent','2025-12-03','Chaka Daley – Head Coach','email.mscoccer@umich.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Clark','Clark','C','D3','NEWMAC','Worcester, MA','Intro Sent','2025-12-03','Samuel Matteson – Head Coach','smatteson@clarku.edu','Likely',null,true,E'Sent MIT camp follow up email\nHas a shared engineering program with Columbia','Follow up with MLS NEXT Fest Update',null,null),
('Ohio State','Ohio State','C','D1','Big Ten','Columbus, OH','Ongoing Conversation','2025-12-03','Brian Maisonneuve – Head Coach','maisonneuve.1@osu.edu','Target','Completed',true,'wanted recruiting questionaire',E'Follow up with MLS NEXT Fest Update\nComplete Recruiting questionaire',null,null),
('University of Portland','Portland','C','D1','West Coast Conference (WCC)','Portland, OR','Intro Sent','2025-12-03','Nick Carlin-Voigt – Head Coach','ncarlinv@up.edu','Target',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Colgate','Colgate','C','D1','Patriot League','Hamilton, NY','Ongoing Conversation','2025-12-03','Erik Ronning - Head Coach','eronning@colgate.edu','Reach','Completed',true,E'Yes in Az\nWill try to see a game\nNo engineering program, but has applied mathematics and other hard sciences\nEmailed about MIT Camp and Coach Brown responded. Not going to be at the camp. Are starting to work on 2027s. Invited to their camp which is on August 1-2.','Follow up with MLS NEXT Fest Update',null,null),
('Emory','Emory','C','D3','UAA','Atlanta, GA','Intro Sent','2025-12-03','Cory Greiner – Head Coach','cgreiner@emory.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null);

-- Block 5: Tier C schools — part 2 (9 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Santa Clara University','Santa Clara','C','D1','West Coast Conference (WCC)','Santa Clara, CA','Intro Sent','2025-12-03','Cameron Rast – Head Coach; Jon del Rosario – Associate Head Coach; Ryan Hopkins – Assistant Coach','crast@scu.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('UC Santa Barbara (UCSB)','UCSB','C','D1','Big West','Santa Barbara, CA','Intro Sent','2025-12-03','Tim Vom Steeg – Head Coach; Greg Wilson – Associate Head Coach; Leo Farfan – Assistant Coach','tvsteeg@ucsb.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('University of Wisconsin Madison','Wisconsin','C','D1','Big Ten','Madison, WI','Intro Sent','2025-12-03','Neil Jones – Head Coach','NWJ@athletics.wisc.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('U of Maryland','Maryland','C','D1','Big Ten','College Park, MD','Intro Sent','2025-12-03','Sasho Cirovski – Head Coach','sasho@umd.edu','Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Princeton','Princeton','C','D1','Ivy League','Princeton, NJ','Ongoing Conversation','2025-11-28','Jim Barlow – Head Coach','jimbarlo@princeton.edu','Far Reach','Completed',true,E'Academics\nTest Scores\nEvents\nNot in Arizona',E'Follow up with MLS NEXT Fest Update.\nInclude info about academics and SATs.',null,null),
('Tufts','Tufts','C','D3','NESCAC','Medford, MA','Ongoing Conversation','2025-11-28','Kyle Dezotell – Head Coach','menssoccer@tufts.edu','Far Reach','Completed',true,E'Keep them updated\nNot it Arizona\nResponded generically pushing id camps\nSent MIT camp follow up email\nCoach Dezotell did college talk on day 1 - Focused on winning mentality',E'Follow up with MLS NEXT Fest Update.\nFollow up after NCAA tournament.',null,null),
('Johns Hopkins','Hopkins','C','D3','Centennial Conference','Baltimore, MD','Ongoing Conversation','2025-12-03','Craig Appleby – Head Coach','hopkinsmenssoccer@jhu.edu','Far Reach','Completed',true,E'Asked us to keep them posted with soccer and academic updates!\nResponded asking for transcript & test scores (Sent)\nCoached your team on day 1 of MIT Camp','Follow up with MLS NEXT Fest Update',null,null),
('Dartmouth','Dartmouth','C','D1','Ivy League','Hanover, NH','Intro Sent','2025-11-28','Connor Klekota – Head Coach','msoccer@dartmouth.edu','Far Reach',null,true,E'Sent MIT camp follow up email, but no response\nNo interaction with Finn\nHas Engineering program combined with AB program','Follow up with MLS NEXT Fest Update',null,null),
('Bowdoin','Bowdoin','C','D3','NESCAC','Brunswick, ME','Ongoing Conversation','2025-12-03','Scott Wiercinski – Head Coach','swiercin@bowdoin.edu','Far Reach','Completed',true,'Coach Banadda will be in AZ','Follow up with MLS NEXT Fest Update',null,null);

-- Block 6: Tier C schools — part 3 (9 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Stanford','Stanford','C','D1','ACC (men''s soccer starting 2024)','Stanford, CA','Ongoing Conversation','2025-11-30','Jeremy Gunn – Head Coach','smsoccer@stanford.edu','Far Reach','To Do',true,E'In Arizona\nID Camp','Follow up with MLS NEXT Fest Update',null,null),
('UCLA','UCLA','C','D1','Big Ten (men''s soccer)','Los Angeles, CA','Intro Sent','2025-11-28','Ryan Jorden – Head Coach','msoccer@athletics.ucla.edu','Far Reach','Completed (no email yet)',true,'ID Camp','Follow up with MLS NEXT Fest Update',null,null),
('Notre Dame','Notre Dame','C','D1','ACC','South Bend, IN','Ongoing Conversation','2025-12-01','Chad Riley – Head Coach','criley@nd.edu','Far Reach','Not Available',true,E'In AZ\nID Camp','Follow up with MLS NEXT Fest Update',null,null),
('Amherst','Amherst','C','D3','NESCAC','Amherst, MA','Ongoing Conversation','2025-12-03','Justin Serpone – Head Coach','jserpone@amherst.edu','Far Reach','Completed',true,E'FL ID camp (2/6-2/8)\nArizona?','Follow up with MLS NEXT Fest Update',null,null),
('Northwestern','Northwestern','C','D1','Big Ten','Evanston, IL','Intro Sent','2025-12-03','Russell Payne – Head Coach','menssoccer@northwestern.edu','Far Reach','Completed',true,E'ID Camp\nRQ','Follow up with MLS NEXT Fest Update',null,null),
('Colby','Colby','C','D3','NESCAC','Waterville, ME','Ongoing Conversation','2025-12-03','Sean Elvert – Head Coach','selvert@colby.edu','Far Reach','Completed',true,'Yes in Arizona','Follow up with MLS NEXT Fest Update',null,null),
('Williams','Williams','C','D3','NESCAC','Williamstown, MA','Intro Sent','2025-12-03','Steffen Siebert – Head Coach','ss40@williams.edu','Far Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Berkeley','Berkeley','C','D1','Pac-12 (men''s soccer)','Berkeley, CA','Intro Sent','2025-12-03','Leonard Griffin – Head Coach','calsoccer@berkeley.edu','Far Reach',null,true,'','Follow up with MLS NEXT Fest Update',null,null),
('Wentworth Institute of Technology','Wentworth','Nope','D3','CCC','Boston, MA','Intro Sent','2025-08-06','Matt O''Toole – Head Coach','msoccer@wentworth.edu',null,null,true,E'Responded asking who his coach was & to fill out Recruiting Questionnaire\nSent MIT camp follow up email\nHas engineering program\nOn the less competitive side academically','',null,null);

-- Block 7: Nope category (13 schools)
insert into public.schools (name,short_name,category,division,conference,location,status,last_contact,head_coach,coach_email,admit_likelihood,rq_status,videos_sent,notes,next_action,next_action_owner,next_action_due) values
('Suffolk','Suffolk','Nope','D3','CCC','Boston, MA','Intro Sent','2025-08-02','Bill Maddock - Head Coach','wmaddock@suffolk.edu',null,null,true,E'Sent MIT camp follow up email\nNo engineering program, but has mathematics and other hard sciences','',null,null),
('Brandeis','Brandeis','Nope','D3','UAA','Waltham, MA','Intro Sent','2025-08-02','Gabe Margolis – Head Coach','menssoccer@brandeis.edu',null,null,true,E'Sent MIT camp follow up email\nNo engineering program, but has applied mathematics and other hard sciences','',null,null),
('DU','DU','Nope','D1','Summit League','Denver, CO','Not Contacted',null,'Jamie Franks – Head Coach','denversoccer@du.edu',null,null,false,'','',null,null),
('Harvard','Harvard','Nope','D1','Ivy League','Cambridge, MA','Not Contacted',null,'Josh Shapiro – Head Coach','msoccer@fas.harvard.edu',null,null,false,'','',null,null),
('San Jose State University (SJSU)','SJSU','Nope','D1','Mountain West','San Jose, CA','Not Contacted',null,'Simon Tobin – Head Coach; Alex Romera – Associate Head Coach; Ignacio Hernandez – Assistant Coach','simon.tobin@sjsu.edu',null,null,false,'','',null,null),
('UC Irvine (UCI)','UC Irvine','Nope','D1','Big West','Irvine, CA','Not Contacted',null,'Yossi Raz – Head Coach; Chris Volk – Associate Head Coach; Edward Koser – Assistant Coach','yraz@uci.edu',null,null,false,'','',null,null),
('Clemson','Clemson','Nope','D1','ACC','Clemson, SC','Not Contacted',null,'Mike Noonan – Head Coach','msoccer@clemson.edu',null,null,false,'','',null,null),
('Rose-Hulman Institute of Technology','Rose-Hulman','Nope','D3','Heartland Collegiate Athletic Conference (HCAC)','Terre Haute, IN','Not Contacted',null,'Sean Helliwell - Head Men''s Soccer Coach','helliwel@rose-hulman.edu',null,null,false,'','',null,null),
('MIT','MIT','Nope','D3','NEWMAC','Cambridge, MA','Ongoing Conversation','2025-12-03','Ken Bovell – Head Coach','kbovell@mit.edu','Far Reach','Completed',true,E'Not in AZ\nWant updates\nSent MIT camp follow up email, but no response back\nCoach Ortiz coached Finn''s team on day 2\nExtracurriculars are big for acceptance\nEmailed on 3/15 with update\nEmailed about PHX on 2/12 (Response from Sam to Finn''s email.)','Follow up with MLS NEXT Fest Update',null,null),
('Caltech','Caltech','Nope','D3','SCIAC','Pasadena, CA','Ongoing Conversation','2025-12-03','Duncan Gillis – Head Coach','dgillis@caltech.edu','Far Reach','Completed',true,E'Need a 1500 SAT to be competitive.\nNeed a 1500 SAT to be competitive (12/1/2025)\nGot an email from Coach DeCoster saying that they''re interested but that they need to beef up STEM academics and extracurricular.','Follow up with MLS NEXT Fest Update',null,null),
('Penn','Penn','Nope','D1','Ivy League','Philadelphia, PA','Not Contacted',null,'Brian Breen – Interim Head Coach','bbreen@upenn.edu',null,null,false,'','',null,null),
('UC San Diego','UCSD','Nope','D1','Big West','La Jolla, CA','Not Contacted',null,'Jon Pascale – Head Coach','jpascale@ucsd.edu',null,null,false,'','',null,null);
